### ISSUE TITLE
Add comparable version to python-ldap

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#110]
``__version__`` is a string, which makes it hard to sort and compare on. We should add ``__version_info__`` as tuple of ints and strings to ``ldap.pkginfo``.

Apropos ``ldap.pkginfo``, the pseudo-standard for package data is ``name.__about__``. Donald started it a while ago and several projects have adopted the standard, e.g. cryptography and my projects, too. ``ldap.pkginfo`` is pretty new. Can we ditch it in favor of ``ldap.__about__``?

## File format

https://github.com/latchset/custodia/blob/d12f7618523685f05bce58e0bb931891259398dc/src/custodia/__about__.py#L3-L19

## include in setup.py

The format is designed to be imported by regular code and read+exec by setup.py.

https://github.com/latchset/custodia/blob/987afad188ec2247442a33be00004434cb03c691/setup.py#L28-L30

**Comment by encukou** [comment]
Shouldn't dunder names should be invented in PEPs, rather than in individual projects? I reckon if the semantics are not standardized, a normal name should work just as well.

So, `ldap.pkginfo.version_info` (and `ldap.version_info`, `ldif.version_info`, etc.) would be my suggestion.

**Comment by encukou** [comment]
The current standard for versions is PyPA's PEP 440, implemented in [packaging.version.Version](https://packaging.pypa.io/en/latest/version/#packaging.version.Version). There's no canonical "sortable tuple" format.
As [importlib.metadata](https://docs.python.org/3.8/library/importlib.metadata.html) is added into Python, I'd rather start deprecating the practice of providing this information in code.
