### ISSUE TITLE
Possible performance regression with LDAPBytesWarning

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#133]
From https://github.com/python-ldap/python-ldap/pull/128#issuecomment-351941287

I suspect (without profiling) that warnings are a performance regression for ``add*`` and ``search*``. All add op take a ``modlist``, all search ops take an optional ``attrlist``. The lists can be pretty long and we do the full warning dance for every entry. We should only warn once per operation.

**Comment by encukou** [comment]
If warnings cause performance issues, fix your code to avoid the warnings. Or choose *silent* rather than *warn* in production.

Also, this is only relevant for Python 2, which has less than 3 months of support left.
I'll go ahead and close it now.
