### ISSUE TITLE
Some default arguments are not compatible with bytes_mode=True

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#147]
With ``bytes_mode=True``, all arguments must be bytes. However some functions have default keyword arguments of type str (unicode). One example is ``search_ext(..., filterstr='(objectClass=*), ...')``.
  
## function signature

- [x] ``simple_bind(self,who='',cred='',serverctrls=None,clientctrls=None)``
- [x] ``simple_bind_s(self,who='',cred='',serverctrls=None,clientctrls=None)``
- [x] ``search_ext(self,base,scope,filterstr='(objectClass=*)', ...)``
- [x] ``search_ext_s(self,base,scope,filterstr='(objectClass=*)', ...)``
- [x] ``search(self,base,scope,filterstr='(objectClass=*)', ...)``
- [x] ``search_s(self,base,scope,filterstr='(objectClass=*)', ...)``
- [x] ``search_st(self,base,scope,filterstr='(objectClass=*)', ...)``
- [x] ``search_subschemasubentry_s(self,dn='')``
- [x] ``find_unique_entry(self,base,scope=ldap.SCOPE_SUBTREE,filterstr='(objectClass=*)', ...)``
- [x] ``read_rootdse_s(self, filterstr='(objectClass=*)', attrlist=None)``

## function body

- [x] ``search_subschemasubentry_s``
- [x] ``read_subschemasubentry_s``
- [x] ``find_unique_entry``
- [x] ``read_rootdse_s``
- [x] ``get_naming_contexts``
- [x] ``ReconnectLDAPObject._apply_last_bind``  

## After fixing this
- [ ] Remove `filterstr` workaround in `Tests/t_ldap_syncrepl.py`

**Comment by anazmy** [comment]
Could this be related ?
~~~
Dec 31 05:46:28 server systemd: Starting IPA key daemon...
Dec 31 05:46:29 server ipa-dnskeysyncd: ipa         : INFO     LDAP bind...
Dec 31 05:46:29 server ipa-dnskeysyncd: ipa         : INFO     Commencing sync process
Dec 31 05:46:29 server ipa-dnskeysyncd: Traceback (most recent call last):
Dec 31 05:46:29 server ipa-dnskeysyncd: File "/usr/libexec/ipa/ipa-dnskeysyncd", line 114, in <module>
Dec 31 05:46:29 server ipa-dnskeysyncd: while ldap_connection.syncrepl_poll(all=1, msgid=ldap_search):
Dec 31 05:46:29 server ipa-dnskeysyncd: File "/usr/lib64/python2.7/site-packages/ldap/syncrepl.py", line 355, in syncrepl_poll
Dec 31 05:46:29 server ipa-dnskeysyncd: add_intermediates=1, add_ctrls=1, all = 0
Dec 31 05:46:29 server ipa-dnskeysyncd: File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 735, in result4
Dec 31 05:46:29 server ipa-dnskeysyncd: resp_data = self._bytesify_results(resp_data, with_ctrls=add_ctrls)
Dec 31 05:46:29 server ipa-dnskeysyncd: File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 260, in _bytesify_results
Dec 31 05:46:29 server ipa-dnskeysyncd: for (dn, fields, ctrls) in results
Dec 31 05:46:29 server ipa-dnskeysyncd: File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 218, in _maybe_rebytesify_text
Dec 31 05:46:29 server ipa-dnskeysyncd: assert isinstance(value, text_type), "Should return text, got bytes instead (%r)" % (value,)
Dec 31 05:46:29 server ipa-dnskeysyncd: AssertionError: Should return text, got bytes instead ('1.3.6.1.4.1.4203.1.9.1.4')
Dec 31 05:46:29 server systemd: ipa-dnskeysyncd.service: main process exited, code=exited, status=1/FAILURE
Dec 31 05:46:29 server systemd: Unit ipa-dnskeysyncd.service entered failed state.
~~~

**Comment by tiran** [comment]
@anazmy I cannot reproduce your traceback. Which version of FreeIPA and python-ldap / pyldap are you using?

**Comment by encukou** [comment]
This will hold 3.0 back :(

**Comment by encukou** [comment]
Should be fixed in https://github.com/python-ldap/python-ldap/pull/152

**Comment by encukou** [comment]
... but not everything on the checklist is fixed
