### ISSUE TITLE
result4() mistreats operations with add_ctrls=True

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#149]
For operations with ``add_ctrls=True``, ``l_ldap_result4`` mishandles resp_data.

* ``l_ldap_result4()`` calls ``LDAPmessage_to_python()`` to create ``pmsg``
* ``LDAPmessage_to_python()`` calls ``LDAPControls_to_List()`` to convert server controls to a Python list.
* ``LDAPControls_to_List()`` returns a tuple of ``(oid: str, critical: bool, ber: bytes)``.
* The Python implementation of ``result4`` uses ``_bytesify_results(resp_data, with_ctrls=add_ctrls)`` to convert results. For ``add_ctrls`` it use ``bytesify_result_value`` to convert resp_data.
* ``bytesify_result_value`` wrongly assumes that a ``List[Tuple[str, bool, bytes]]`` is a list of referrals when it's in fact a triple of control values.

Original reported as https://github.com/python-ldap/python-ldap/issues/147#issuecomment-354594575

**Comment by tiran** [comment]
I cannot reproduce the issue and I'm starting to think that my analysis is wrong, too. The ``pmsg`` object is a list of two or three elements. The first element is dn (always unicode). The second is a dict of unicode keys. The third element is the control list ``List[Tuple[str, bool, bytes]]``.

https://github.com/python-ldap/python-ldap/issues/147#issuecomment-354594575 may be caused by an old version of pyldap. I don't see how the error could ever occur with more recent versions of python-ldap. On the other hand the bytesification code is complicated and partly hard to understand.

**Comment by encukou** [comment]
The only actionable issue I can see here is *clean up the bytesification code*. I don't think that needs to be tracked here.
