### ISSUE TITLE
Warning and error handling in _bytesify_input is too inflexible

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#166]
The way how ``_bytesify_input`` handles errors and warnings is too inflexible:

https://github.com/python-ldap/python-ldap/blob/ad46c1104ea40117f8fb0fd08653517743f94723/Lib/ldap/ldapobject.py#L125-L158

* For ``bytes_mode=None`` (default), the function emits a bytes warning when the input is text, then encodes it as UTF-8 bytes. Warnings are slow and can cause performance regressions (see #133). The warnings are always emitted, even when warnings are disabled and not shown to the user. The warnings module does not allow early opt-out.
* For ``bytes_mode=False`` (strictly future-compatible) there is no warnings mode at all. When the function is called with bytes as input, it always fails with ``TypeError``. TypeErrors make it really, really hard to port an existing application to future compatible API. There should be a mode that emits just warnings.

## Proposal

I suggest that we introduce a ``bytes_warning`` flag:

* ``bytes_warning=BYTES_WARNINGS_SILENT`` emits no warnings and doesn't raise TypeError for ``bytes_mode`` None, True, and False.
* ``bytes_warning=BYTES_WARNINGS_WARN`` emits a warning when input is text for ``bytes_mode=None`` / ``bytes_mode=True`` or input is bytes for ``bytes_mode=False``.
* ``bytes_warning=BYTES_WARNINGS_ERROR`` raises a TypeError when input is text for ``bytes_mode=None`` / ``bytes_mode=True`` or input is bytes for ``bytes_mode=False``.
*  ``bytes_warning=None`` (default) depends on ``bytes_mode``:
    * ``bytes_mode=None`` -> ``BYTES_WARNINGS_WARN``
    * ``bytes_mode=True`` -> ``BYTES_WARNINGS_ERROR``
    * ``bytes_mode=False`` -> ``BYTES_WARNINGS_ERROR``

The flags are defined as:

```
BYTES_WARNINGS_SILENT = 0
BYTES_WARNINGS_WARN = 1
BYTES_WARNINGS_ERROR = 2
```

**Comment by encukou** [comment]
The proposal looks reaonable. I hope to fully get to it next week. (initial nitpick: let's use `bytes_warning='warn'` instead of numbers.)

I'm also thinking about doing this *as* 3.1. I feel the betas aren't useful any more; AFAIK there's only you trying them out.

**Comment by tiran** [comment]
Do you want to address the issue for 3.0 or shall we get 3.0.0 out now and implement this for 3.1?

I'm fine with getting 3.0 out now. But we should make ``bytes_mode_hardfail`` attribute a private attribute before 3.0 gets out.

**Comment by encukou** [comment]
I played around with the idea. 
How about making `bytes_mode` itself hold the, well, mode? That is, add `bytes_mode == 'warn'` and `bytes_mode == 'warn'` options?

See the commit linked above for a (test-less) implementation.

**Comment by tiran** [comment]
How do you plan to encode ``bytes_mode=False`` with warning?

**Comment by encukou** [comment]
Argh. I misread the most important part of the issue, didn't I.

About deprecating `bytes_mode_hardfail` -- it's been part of `pyldap` for a while. It's even gets pickled. Let's remove it in 3.0.
Only renaming it isn't worth the churn. Let's put this in 3.0. Can you prepare a PR?

**Comment by tiran** [comment]
Well, you skipped the most important part for my use case. :)

What do you want to use instead of ``bytes_mode_hardfail``?

**Comment by encukou** [comment]
`bytes_warnings`, as in your proposal, sounds good. With string values,
preferably.

**Comment by tiran** [comment]
It's very unlikely that I will have time to develop and test a patch before Feb 6th. I'm busy with DevConf CZ preparations and will have a week of meetings and travel after DevConf.

## Proposition
* Make ``bytes_mode_hardfail`` attribute private since we will probably not support in 3.1
* Release 3.0.0 now
* Roll out 3.1.0 mid February.

**Comment by encukou** [comment]
Renaming `bytes_mode_hardfail` needs some care as well. I'll work on implementing your proposal instead.
