### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by encukou** [python-ldap/python-ldap#167]
I don't think the betas are useful any more. The release process is now clear, and it looks like anyone who's testing the betas is either fine with them or knows to hold off upgrading to 3.0 until all their problems are solved.
And unlike December, there aren't major holidays in front of us.
So, I'd like to release the next version as 3.0 final, and start doing additional fixes in 3.1+.

### [Maintainer checklist](https://python-ldap.org/en/latest/contributing.html#instructions-for-release-managers):

* [x]    Bump all instances of the version number.
* [x]    Go through all changes since last version, and add them to CHANGES.
* [x]    Run Additional tests and scripts as appropriate, fix any regressions.
* [x]    Change the release date in CHANGES.
* [x]    Merge all that (using pull requests). (https://github.com/python-ldap/python-ldap/pull/180)
* [x]    Run python setup.py sdist, and smoke-test the resulting package (install in a clean virtual environment, import ldap).
* [x]    Create Git tag python-ldap-{version}, and push it to GitHub and Pagure.
* [x]    Release the sdist on PyPI.
* [x]    Announce the release on the mailing list. Mention the Git hash.
* [x]    Add the release’s log from CHANGES on the GitHub release page.

**Comment by peterpakos** [comment]
Any idea when we can expect this to happen?

Can we count on new python-ldap package being released in RHEL/CentOS repositories?

Cheers.

**Comment by tiran** [comment]
* RHEL 7 will most likely never see an update to python-ldap 3.0. The current version works.
* Fedora rawhide already has 3.0.0-beta4. For a F27 package, you have to change your dependencies to use python-ldap and and python3-pyldap

```
%if 0%{?fedora} > 28
Requires:  python3-ldap >= 3.0
%else
Requires:  python3-pyldap
%endif
```

**Comment by peterpakos** [comment]
This makes some people's lives somewhat difficult...

How do I define package requirements for a module that is Python 2 and 3 compatible that can then be rpm packaged for CentOS 7?

PyPI's pyldap seems to satisfy both Python 2 and 3 requirements but its not available in CentOS repositories.

python-ldap works great in Python 2 and is available in CentOS repositories but breaks compatibility with Python 3.

Any recommendation or suggestion greatly apreciated.

Background: https://github.com/peterpakos/checkipaconsistency/pull/41
Looping in @JensTimmerman for visibility.

**Comment by encukou** [comment]
Note that PyPI's pyldap will be retired after python-ldap 3.0 is released – it will be replaced by a dummy package that requires python-ldap. See the [pyldap repo](https://github.com/pyldap/pyldap/).

To make python-ldap work with python3 on CentOS, you (or someone) should package it in EPEL. Name it `python3-ldap` or `python36-ldap` to avoid conflict with RHEL's python2 version.

To get it in Red Hat Software Collections, file a request with Red Hat – there's not much we can do there from the community side.

Also note that the release should not break anything: if things work now, they should continue working after distros upgrade to 3.0 (if they ever do). File bugs for the distribution if that's not the case.

**Comment by encukou** [comment]
Released.
I'll be online the next week, in case this sets something on fire.

**Comment by intgr** [comment]
Thank you so much for merging Python 3 support and moving from SourceForge to GitHub. Much appreciated!
