### ISSUE TITLE
PIp install fails, missing sasl.h

### ISSUE THREAD

**Issue by heikkimu** [python-ldap/python-ldap#168]
pip install python-ldap fails miserably for the lack of the sasl.h.

It can be fixed by setting:
`export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include/sasl"` and then running the pip-install.

More at: https://stackoverflow.com/questions/22079173/installing-py-ldap-on-mac-os-x-mavericks-missing-sasl-h

Steps to reproduce: 
`pip install python-ldap`

Operating system: 
Mac os

Python version: 
2.7.1

python-ldap version: 
2.5.2

**Comment by tiran** [comment]
Which build environment are you using? I'm not a macOS expert. It looks like you are using the platform SDK and XCode.

Please try again with 3.0.0 beta, ``pip install --pre --upgrade python-ldap``. The latest version correctly includes ``sasl/sasl.h``.

**Comment by tiran** [comment]
The problem with sasl.h has been fixed in revisions b0c908149af50bd3645744091ddf3697c4e02750 and 5729d06ff5eda1e30858ffaf19e566e9b5283487. python-ldap 3.0 includes ``sasl/sasl.h``.

**Comment by encukou** [comment]
Please re-open if you get this problem with python-ldap 3.x. (As said above, it's currently in beta; install it with `pip install --pre`.)

**Comment by ttang235** [comment]
Had a similar problem

**Comment by dgarberj** [comment]
Thanks for this :)
