### ISSUE TITLE
Exceptions don't include the message id they are an exception for

### ISSUE THREAD

**Issue by gwvandesteeg** [python-ldap/python-ldap#177]
**Issue description:**
When using the async methods and polling for results using the result(msg=RES_ANY), an exception can get raised since one of the async calls generated caused the error.
The exception raised does not include the message id of the request that caused the exception.
Having 10 outstanding requests and receiving an exception for one (ie. ldap.ALREADY_EXISTS) and not knowing which request this was for since we're not receiving the msgid in the response.

**Steps to reproduce:** 
connect to python
alternate an add and a search query using the same query three times (each) using the async methods (or randomise the order)
poll for results until you've received a response for each outstanding request.
all the searches should complete, one of the adds should complete, and two of the adds should've failed, but which add.. which message ids.

**Operating system:** 
Linux

**Python version:** 
2.7+

**python-ldap version:** 
all

**Comment by encukou** [comment]
Thank you for reporting the issue!
Would you be willing to a propose fix, or perhaps a (failing) test case to illustrate how you would like this to be solved?

**Comment by tiran** [comment]
This should be easy to solve by changing ``PyObject* LDAPerror(LDAP*, char* msg);`` to ``PyObject* LDAPerror(LDAP*, char* msg, int msgid);``. We also need a value to signal that we don't have a value msgid. A msgid is a positive int except for two special cases: ``LDAP_RES_ANY`` is defined as ``-1`` and ``LDAP_RES_UNSOLICITED`` as ``0``. Any value small than -1 should do the trick.

**Comment by gwvandesteeg** [comment]
That is basically the same idea I had when looking at the code base,  initialise msgid to None and then set it if we get one,  or a negative value will do just as well for no message id present.

**Comment by spaceone** [comment]
I would like to see this as well :-)
