### ISSUE TITLE
What is the correct way to change LDAPObject from SimpleLDAPObject?

### ISSUE THREAD

**Issue by somay** [python-ldap/python-ldap#205]
python-ldap version: 3.0.0
Python version: 3.5.2

The doc says `ldap.initialize()` uses `ldap.ldapobject.LDAPObject` and also says

> Internally LDAPObject is set to SimpleLDAPObject by default.

It seems to me that *by default* implies that `LDAPObject` can be changes to `ReconnectLDAPObject` or custom class inheriting `ldap.resiter.ResultProcessor` or any other valid classes and then I call `ldap.initialize()` and successfully get a object of my registered class.
The way to change the *default* is not documented though.

I found that assigning a desired class to `ldap.function.LDAPObject` causes the aforementioned behaviour.
But this method seems tricky to me and I wonder it is your expected usage of this library.

It would be great if the things below is clarified in the doc.
Being obvious also through API design would be superb.

* What is the recommended way to use classes other than `SimpleLDAPObject`?
* Which is recommended whether calling `ldap.initialize()` or directly instantiating `ldap.ldapobject.SimpleLDAPObject` or such?

**Comment by tiran** [comment]
``ldap.initialize`` just creates an instance of ``LDAPObject``, which is an alias for ``SimpleLDAPObject``. It's basically a one-liner and doesn't do any extra work. I recommend that you use ``ldap.initialize`` if you want default behavior. In case you need a reconnecting LDAP client or Resiter, then instantiate the classes directly.

@encukou we should clarify this in the documentation.

By the way, I'm going to obsolete Resiter and include the feature into ``LDAPObject``, see #204.

**Comment by somay** [comment]
Thank you a lot @tiran for answering very quickly!
So eventually the issue you mentioned will be resolved and I needn't use my custom class. Great improvement!

**Comment by somay** [comment]
I here list the causes of my confusion for you to choose direction of documetation improvement.

My confusion resulted from:

* `ldap.initialize()` is on very top of documentation.
* `ldap.initialize()` is more easy to import than `ldap.ldapobject`.
* Where `*LDAPObject` is from (actually from `ldap.ldapobject`) is not (as far as I read) documented. 
* `ldap.ldapobject` is not in table of contents in left menu.

**Comment by encukou** [comment]
Re-opening this, since we do need to change the documentation
