### ISSUE TITLE
Retrieve attributes of user, using DN

### ISSUE THREAD

**Issue by darryllane** [python-ldap/python-ldap#207]
Apologies I have scowered the docs and cant find anything on how to use a Users DN to retrieve their attributes. The search function doesnt seem appropriate here as we dont need to search we know the exact location of the user. Have I missed something?

**Comment by tiran** [comment]
If you already know the DN and just want to retrieve some attributes, then you can use search with SCOPE_BASE and a list of attribute names.

**Comment by encukou** [comment]
I hope that answered your question. Please re-open this issue if it didn't!
