### ISSUE TITLE
python-ldap.org is not reachable - Cloudflare: CNAME Cross-User Banned

### ISSUE THREAD

**Issue by stevepiercy** [python-ldap/python-ldap#232]
Issue description:
https://www.python-ldap.org/en/latest/ is not reachable.
```
Error 1014 Ray ID: 43caf5c8ffdd8ce1 • 2018-07-19 05:59:06 UTC
CNAME Cross-User Banned
What happened?
You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.

What can I do?
If you are interested in learning more about Cloudflare, please visit our website.

Cloudflare Ray ID: 43caf5c8ffdd8ce1 • Your IP: 2603:3004:212:2000:5b5:a5f9:f774:aec9 • Performance & security by Cloudflare
```

**Comment by encukou** [comment]
Hello,
This came at quite a bad time: I'm on vacation, and I'm afraid still the
single point of failure when it comes to the website :(
I won't have acess to a computer until Friday. Please use
python-ldap.readthedocs.io directly until then.
Very sory for the inconvenience.

**Comment by stevepiercy** [comment]
No worries. I noticed it only because I ran a linkcheck in Sphinx for the Pyramid Community Cookbook. Enjoy your vacation!

**Comment by encukou** [comment]
I've applied a temporary workaround I found at https://github.com/rtfd/readthedocs.org/issues/4395. It looks like the docs work now. I'll look into it more in a week, when I get back.

**Comment by encukou** [comment]
According to the discussion in https://github.com/rtfd/readthedocs.org/issues/4395, that workaround is good for the long term.

---

The documentation is hosted on Read the Docs, which recently started to use the CloudFlare proxy for HTTPS support.
python-ldap.org previously used the same proxy independently. When Read the Docs switched to CloudFlare, that meant in CloudFlare started proxying to itself, causing this issue.
At the suggestion of one of the commenters, I turned one of the proxy layers off. A RTD contributor then verified this is a right solution.

python-ldap.org still uses CloudFlare for DNS (specifically, for CNAME flattening).

**Comment by stevepiercy** [comment]
Thanks for the follow up. I kept the original link and it's working fine.
