### ISSUE TITLE
'LDAP' object has no attribute 'sasl_interactive_bind_s'

### ISSUE THREAD

**Issue by papaslen** [python-ldap/python-ldap#236]
Issue description:

I`m trying to use Kerberos Authentication using python-ldap. So, my steps are:

`self.ldap_con = ldap.initialize(ldap_conn_string)  # initialize ldap object
self.ldap_con.sasl_gssapi_bind_s()  # This throws exc 'LDAP' object has no attribute 'sasl_interactive_bind_s'`

This Exception appears both on sasl_gssapi_bind_s() and sasl_interactive_bind_s() methods.

Steps to reproduce: 
1. Use python 2.7 environment
2. Initialize python-ldap
3. Try to use **sasl_gssapi_bind_s()** or **sasl_interactive_bind_s()**

Operating system: 
Win 7

Python version: 
Python 2.7

python-ldap version: 
pythin-ldap 3.1.0

**Comment by tiran** [comment]
You have a build of python-ldap and libldap without Cyrus SASL bindings. You need to figure out how to rebuild python-ldapw with optional components.

**Comment by encukou** [comment]
Please re-open if that doesn't help.
