### ISSUE TITLE
ldap_destroy on gc

### ISSUE THREAD

**Issue by igron99** [python-ldap/python-ldap#238]
Issue description:

Does ldap struct need to be destroyed at the end of life?

Steps to reproduce: 

append ldap_destroy to gc function

Operating system: 
all
Python version: 
all
python-ldap version: 
3.1.0

**Comment by igron99** [comment]
OK, is it normal, that unbind_ext make work, that destructor must do?
if we call bind, then unbind and bind again we get SEGFAULT...

**Comment by encukou** [comment]
Hi,

The [unbind_*](http://python-ldap.org/en/latest/reference/ldap.html#ldap.LDAPObject.unbind) functions immediately close the connection and free resources.
This also happens [when the LDAPObject is garbage-collected](https://github.com/python-ldap/python-ldap/blob/master/Modules/LDAPObject.c#L36). So, you do not need to call unbind_* yourself.

I hope this answers your question.
