### ISSUE TITLE
Incompatability in python-ldap between Py2.7.12 and Py2.7.15?

### ISSUE THREAD

**Issue by nv596r** [python-ldap/python-ldap#239]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description: modlist is interpreting string as array

Steps to reproduce: 

    import ldap.modlist as ml
    
    d = { 'a': 'word', 'cn': 'ou=example,ou=com' }
    e = { 'a': 'other word', 'cn': 'ou=example,ou=com'}
    
    ldif = ml.modifyModlist(d, e)
    print str(ldif)

The output under 2.7.12 python-ldap==2.4.38 (which appears correct)

>  [(1, 'a', None), (0, 'a', 'other word')]

The output under 2.7.15 python-ldap==3.1.0 (which appears incorrect)

>  [(1, 'a', None), (0, 'a', ['o', 't', 'h', 'e', 'r', ' ', 'w', 'o', 'r', 'd'])]

Operating system: Redhat Enterprise 6.x

Python version: differences between 2.7.12 (python-ldap==2.4.38) and 2.7.15 (python-ldap==3.1.0)

python-ldap version: differences between 2.7.12 (python-ldap==2.4.38) and 2.7.15 (python-ldap==3.1.0)

**Comment by tiran** [comment]
You are depending on undefined and unintended behavior. LDAP attribute values are always multi-valued (lists). python-ldap 3.1 enforces lists as attributes. You must write your attribute dict as ``{'a': ['word'], 'cn': ['ou=example,ou=com']}``.

I used bisect to find the commit that dropped support for strings. It was 17b4000d7d0eaab602098ac3aa5d858373d659af. The ``filter`` function has a special case for strings.

**Comment by nv596r** [comment]
Thanks much to Tiran for explaining. Closing issue.

**Comment by heyakyra** [comment]
Can a string still optionally be used as the last element, `mod_vals`, in a `modlist` tuple provided to the `modify()` method of an `LDAPObject`?

If not, this comment may be out of date: 
https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/ldapobject.py#L615
