### ISSUE TITLE
Can't search objects directly below root

### ISSUE THREAD

**Issue by dmulder** [python-ldap/python-ldap#241]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

I can search for objects if I specify a dn below the 'root', but if I try to search at the top of the tree, I get an error:
```
  File "test_ldap_search.py", line 19, in <module>
    result = l.search_s(realm_dn, ldap.SCOPE_ONELEVEL, '(objectCategory=Container)', ['cn'])
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 831, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 825, in search_ext_s
    return self.result(msgid,all=1,timeout=timeout)[1]
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 717, in result
    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 721, in result2
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 728, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 735, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 308, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 292, in _ldap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'info': u'000004DC: LdapErr: DSID-0C0906DD, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1771', 'desc': u'Operations error'}
```

Steps to reproduce: 

```
import ldap

server = '<server address>'
realm = '<realm>'
realm_dn = ','.join(['DC=%s' % part for part in realm.lower().split('.')])

l = ldap.initialize('ldap://%s' % server)
auth_tokens = ldap.sasl.gssapi('')
l.sasl_interactive_bind_s('', auth_tokens)

system = 'CN=System,%s' % realm_dn

print('Containers at system:')
result = l.search_s(system, ldap.SCOPE_ONELEVEL, '(objectCategory=Container)', ['cn'])
for i in result:
    print(i[-1]['cn'])

print('Containers at top:')
result = l.search_s(realm_dn, ldap.SCOPE_ONELEVEL, '(objectCategory=Container)', ['cn'])
for i in result:
    print(i[-1]['cn'])
```

The first search succeeds and prints all the containers in System. I'd expect the second search to find the 'System' container (among others), but it doesn't. Instead I get the error.

Operating system: 
openSUSE Tumbleweed

Python version: 
\> python --version
Python 2.7.15

python-ldap version: 
3.1.0

**Comment by dmulder** [comment]
This same search works using the ldap3 python module:

`l = ldap3.Connection(server, user=user, password=password, authentication=ldap3.NTLM, auto_bind=True)`

`print('Containers at top:')`
`l.search(realm_dn, '(objectCategory=Container)', search_scope='LEVEL', attributes= ['cn'])`
`for i in l.entries:`
`    print(i['cn'])`

**Comment by quanah** [comment]
I've adapted the above code to work against a default example database I have in an OpenLDAP server, and it works as designed.  I.e., the issue here does not seem to be with python, but perhaps with
- the LDAP server that was used on the backend
- the DIT doesn't match the query filters being used
- the identity being used doesn't have the permissions to query the root of the DIT

Here's my adapted code:
```
#!/usr/bin/python3
import ldap

server = '10.2.0.74'
realm = 'example.com'
realm_dn = ','.join(['DC=%s' % part for part in realm.lower().split('.')])

l = ldap.initialize('ldap://%s' % server)
l.simple_bind_s("dc=example,dc=com", "secret")
system = 'ou=accounting,%s' % realm_dn

print('Containers at accounting:')
result = l.search_s(system, ldap.SCOPE_ONELEVEL, '(objectClass=inetOrgPerson)', ['cn'])
for i in result:
    print(i[-1]['cn'])

print('Containers at top:')
result = l.search_s(realm_dn, ldap.SCOPE_ONELEVEL, '(objectClass=organizationalUnit)', ['ou'])
for i in result:
    print(i[-1]['ou'])
```

Here's the output:

```
./base.py
Containers at accounting:
[b'May Gaul']
[b'Ann Tully']
[b'Par Chong']
[b'Muriel Oka']
[b'Zyg Chawla']
[b'Biddie Auld']
[b'Byron Evers']
[b'Coors Moree']
Containers at top:
[b'Accounting']
[b'Product Development']
[b'Product Testing']
[b'Human Resources']
[b'Payroll']
[b'Janitorial']
[b'Management']
[b'Administrative']
[b'Peons']
[b'Planning']
[b'KerberosPrincipals']
```

**Comment by quanah** [comment]
In fact, I would note that the error provided:

> ldap.OPERATIONS_ERROR: {'info': u'000004DC: LdapErr: DSID-0C0906DD, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1771', 'desc': u'Operations error'}

clearly indicates that a bind failure.

**Comment by tiran** [comment]
The first examples uses GSSAPI for bind, the ldap3 example uses username+password with NTLM for bind. I assume that either Kerberos/AD integration is not configured on the system or that the principal does not have permission to access AD.

I'd start by debugging if the machine can acquire a TGT and a service ticket.

**Comment by quanah** [comment]
@tiran I think the larger point is there is no demonstrated issue with python-ldap here.  The functionality requested clearly works appropriately.

**Comment by encukou** [comment]
I'll close this. Please re-open if the above doesn't help, or if you have new info.
