### ISSUE TITLE
missing generated password from the server on the extended password modify operation

### ISSUE THREAD

**Issue by akshayadhikari1** [python-ldap/python-ldap#246]
Issue description: 

I was trying to use passwd_s() for various password change operation, what I observed is there is no way to extract the system generated password when we do not provide new password. I checked the logs it does generate the random system password.

Steps to reproduce: 

passwd_s(USER_DN, OLD_PASSWORD, None)

Operating system:
 
Fedora-28

Python version: 

3.6.6

python-ldap version:

2.4.46-3.fc28

**Comment by quanah** [comment]
This works for me:
```
import ldap
l = ldap.initialize('ldap://localhost')
l.simple_bind_s("dc=example,dc=com", "secret")
msgid = l.passwd_s("cn=Marice McCaugherty,ou=Product Testing,dc=example,dc=com", None, None)
password=msgid[1].decode('latin1').split()[1]
print("New password:%s" % password)
```

I get:

```
# ./password.py
New password:Xjt9leMy
```

And I can confirm this password works:

```
# ldapwhoami -x -H LDAP:// -D "cn=Marice McCaugherty,ou=Product Testing,dc=example,dc=com" -w Xjt9leMy
dn:cn=Marice McCaugherty,ou=Product Testing,dc=example,dc=com
```
