### ISSUE TITLE
ldap.dn.escape_dn_chars problem with a single space character

### ISSUE THREAD

**Issue by eriklax** [python-ldap/python-ldap#252]
This may be a very minor problem, but the `ldap.dn.escape_dn_chars` function does not handle strings containing only one space character properly. As both the first and the last characters is a space in such a string.

```
>>> ldap.dn.escape_dn_chars(' ');
'\\\\ '
```

https://github.com/python-ldap/python-ldap/blob/7ce471e238cdd9a4dd8d17baccd1c9e05e6f894a/Lib/ldap/dn.py#L32-L35

I believe the quickest fix would be if the `s[-1]` check were done before the `s[0]`,

**Comment by spaceone** [comment]
This is merged and can be closed!
