### ISSUE TITLE
Return ldap.initialize differ of the documentation

### ISSUE THREAD

**Issue by eamanu** [python-ldap/python-ldap#256]
Hello everybody!

Reading the documentation https://www.python-ldap.org/en/latest/reference/ldap.html#ldap.LDAPObject this tell that and ldap.LDAPObject is returned by ldap.initialize, but currently `ldap.ldapobject.SimpleLDAPObject` is returned. 

I think that this must be clarify on doc. 

Regards!

Operating system: Linux eamanu 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 

Python version: Python 2.7.15rc1

python-ldap version: 3.1.0

**Comment by tiran** [comment]
``ldap.ldapobject.LDAPObject`` is an alias for ``ldap.ldapobject.SimpleLDAPObject``. The documentation incorrectly refers to both classes as ``ldap.LDAPObject`` but the ldap top level name space does not provide these attributes.

**Comment by eamanu** [comment]
> `ldap.ldapobject.LDAPObject` is an alias for `ldap.ldapobject.SimpleLDAPObject`. The documentation incorrectly refers to both classes as `ldap.LDAPObject` but the ldap top level name space does not provide these attributes.

That's right.  My unittest failed because I run ` self.assertIsInstance(ldap.initialize(url), ldap.LDAPObject)`. 

I think that in documentation need to say the real class' name
