### ISSUE TITLE
Python venv can't import python-ldap after uninstalling ldap

### ISSUE THREAD

**Issue by phg49389** [python-ldap/python-ldap#258]
**Issue description:**
Originally it appeared as an AttributeError, saying that ldap didn't have initialize(). After one of the other developers on the team did some debugging, he found that it was because the `import ldap` statement was failing, even though pip freeze showed that python-ldap was installed in the virtual environment. He handed it off to me to solve, and last night I found the issue.

In an earlier build of our project, we had installed the ldap package in our venv (not python-ldap). After python-ldap was installed in the venv, we chose to uninstall ldap to try to prevent ambiguous importing. For whatever reason, python-ldap's ability to be alias-imported as "ldap" got broken when Pip removed the ldap package. (top_level.txt might have something to do with the alias?) 

The solution that I found was to make sure that the packages were mutually exclusive. Uninstalling ldap before python-ldap gets installed lets the import statement work as expected.

To be honest, this is probably an issue with how Pip is coded, rather than the python-ldap package itself. The reason I'm submitting the issue here is because there might be a work-around solution that could rolled out in this package faster than the next Pip release. While compiling python-ldap for installation via Pip, assert that the ldap package is not already installed in the venv. If it is, fail the installation. This would effectively force python-ldap to be mutually exclusive with ldap, and then ldap would have to be uninstalled by the user before python-ldap could be installed.

**Steps to reproduce:** 
1. Create a Python virtual environment
2. `./pip install ldap`
3. `./pip install python-ldap`
4. `./pip uninstall ldap`
5. `./pip freeze` to verify that only python-ldap is installed
6. Run interactive python from the venv
7. In the interactive python, run `import ldap`
8. Expected exception: `ImportError: No module named ldap`

**Operating system:** 
CentOS 7

**Python version:** 
Python 2.7.5
Pip 9.0.1 (and recreated on Pip 18 while writing up this issue)

**python-ldap version:** 
3.1.0

**Comment by encukou** [comment]
Hi,
Pip doesn't handle packages with overlapping files/directories well, and the Pip maintainers don't consider it a priority. (I definitely don't blame them for that, given their hard work on difficult tasks that *are* important for the entire ecosystem. Also, I unfortunately can't find time to dive into Pip internals and helping out.)

Pip issue https://github.com/pypa/pip/issues/4961 tracks a similar problem, if not the same.

Regading the suggested workaround: Pip builds packages in an isolated environment*⁾ and installs the resulting wheel, which means we unfortunately don't really have access to the target environment in the install code.

The name conflict with `ldap` on PyPI is very unfortunate, but not easy to resolve. Same for the problem of the package named `python-ldap` providing a `ldap` module. I explained more at https://github.com/andreif/ldap/issues/1#issuecomment-458144780.


---

\*⁾ *Maybe that's not implemented yet, I don't know how far along the plans are. But cached wheels are definitely used today.*

**Comment by encukou** [comment]
The owner of `ldap` on PyPI generously transferred the name to me, and I've replaced the package with a [placeholder](https://github.com/python-ldap/ldap-pypi-placeholder).

`pip install ldap` now fails with an explanation and instructions to install `python-ldap`.

**Comment by phg49389** [comment]
Sorry for the delayed reply -- you provided a very good answer. Thanks for teaching me some about how Pip packages get installed!
