### ISSUE TITLE
help me!Where is the return value from the LDAP server?

### ISSUE THREAD

**Issue by Git-Banl** [python-ldap/python-ldap#264]
I just joined a company,
Now I want to get the result code from the LDAP server.
Very sad! I can't read your code.
Please help me!
---

Issue description(demand):
I want to distinguish between account password errors and account locking.
What should I do?
Which class or method needs to be overridden?

Python version: 
python2.7

**Comment by encukou** [comment]
Hello,
This depends on the set-up in your company. Please talk to whoever maintains your LDAP servers.

This is an *issue tracker* used for reporting and managing bugs in the software. If you want to discuss or try getting help, please use the mailing list instead.

The documentation is at http://python-ldap.org. Please read it, and if you find something missing from it, or not explained properly, please do open a specific issue here.
