### ISSUE TITLE
error: command 'clang' failed with exit status 1

### ISSUE THREAD

**Issue by MNicholasPro** [python-ldap/python-ldap#266]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
When I used 'pip install python-ldap', it showed me like this 

'clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.1.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c Modules/LDAPObject.c -o build/temp.macosx-10.14-x86_64-3.7/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:3:
    In file included from Modules/common.h:9:
    /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:30:10: warning: non-portable path to file '<String.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
    #include <string.h>
             ^~~~~~~~~~
             <String.h>
    In file included from Modules/LDAPObject.c:3:
    In file included from Modules/common.h:9:
    In file included from /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:30:
    /usr/local/include/string.h:25:10: fatal error: 'plist/Node.h' file not found
    #include <plist/Node.h>
             ^~~~~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'clang' failed with exit status 1'

Steps to reproduce: 
pip install python-ldap 

Operating system: 
mac OS 10.14.3

Python version: 
python 3.7.2

python-ldap version: 
python-ldap 3.1.0

**Comment by encukou** [comment]
I'm not familiar with macOS & Homebrew, but found an answer for a for a similar problem: [use `brew doctor` to find extra files in `/usr/local`](https://stackoverflow.com/a/49316028/99057).
Does that help with your issue?

**Comment by MNicholasPro** [comment]
> I'm not familiar with macOS & Homebrew, but found an answer for a for a similar problem: [use `brew doctor` to find extra files in `/usr/local`](https://stackoverflow.com/a/49316028/99057).
> Does that help with your issue?

Thank you , I will try later.

**Comment by MNicholasPro** [comment]
> > I'm not familiar with macOS & Homebrew, but found an answer for a for a similar problem: [use `brew doctor` to find extra files in `/usr/local`](https://stackoverflow.com/a/49316028/99057).
> > Does that help with your issue?
> 
> Thank you , I will try later.



> > I'm not familiar with macOS & Homebrew, but found an answer for a for a similar problem: [use `brew doctor` to find extra files in `/usr/local`](https://stackoverflow.com/a/49316028/99057).
> > Does that help with your issue?
> 
> Thank you , I will try later.

It works,and thanks for your help.
