### ISSUE TITLE
Ordering SSSRequestControl Dont Work

### ISSUE THREAD

**Issue by cavazquez** [python-ldap/python-ldap#269]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

When i search with SSSREquestControl the  SSSRequestControl(ordering_rules=['uidNumber'])
and  SSSRequestControl(ordering_rules=['-uidNumber']). The result is the same in both.

I use conn.search_ext_s . When the sizelimit is not zero the amount is zero.

Steps to reproduce: 

Operating system: 

Python version: 3.7

python-ldap version: Last

**Comment by spaceone** [comment]
I have the same issue with `slapd 2.4.45`.
How can I debug this? Is this an error in the ldap server or in the `python-ldap` control?

**Comment by spaceone** [comment]
Seems it must be enabled in the `slapd.conf` via
```
moduleload sssvlv
overlay sssvlv
```
http://www.openldap.org/software/man.cgi?query=slapo-sssvlv&apropos=0&sektion=0&manpath=OpenLDAP+2.4-Release&format=html

**Comment by mistotebe** [comment]
Yes, not a bug in python-ldap, if you require the control to be honoured, you have to make it critical. Otherwise the server is permitted to ignore it (especially if it doesn't know how to handle it).
