### ISSUE TITLE
"Operation unavailable without authentication" when using GSSAPI bind

### ISSUE THREAD

**Issue by JonathonReinhart** [python-ldap/python-ldap#275]
I'm running a Samba 4 domain controller (version 4.9.4-Debian).

- Operating system: Debian Buster
- Python version: Python 3.7.3rc1
- python-ldap version: 3.2.0

I can successfully use `ldapsearch` with GSSAPI SASL authentication to search for users:
```
$ kinit someone
...

ldapsearch -Y GSSAPI -H "ldap://samba-dc.ad.example.com" -b "dc=ad,dc=example,dc=com" "(objectClass=user)" sAMAccountName
```

However, when I attempt to use this Python snippet:
```python
import ldap,ldap.sasl
from pprint import pprint

l = ldap.initialize("ldap://samba-dc.ad.example.com", trace_level=100)

rc = l.sasl_gssapi_bind_s()

base = "dc=ad,dc=example,dc=com"
criteria = "(objectClass=user)"
result = l.search_s(base, ldap.SCOPE_SUBTREE, criteria)
pprint(result)
```

It doesn't work, and I get this error:
```
ldap.OPERATIONS_ERROR: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}
```

~~FWIW: I can't get this to work with `ldap3` either: https://github.com/cannatag/ldap3/issues/669~~ That issue is unrelated.

**Comment by tiran** [comment]
Is your libldap linked against MIT or Heimdal Kerberos? MIT KRB5 has an option to print additional debug information with env var ``KRB5_TRACE=/dev/stderr``. Please set it before before you start the process.

What does ``l.whoami_s()`` return? It should return the DN of the user.

**Comment by tiran** [comment]
A success authentication with interactive bind and KRB5 tracing looks like this:

```
>>> import ldap
>>> l = ldap.initialize('ldap://master.ipa.example')
>>> l.sasl_interactive_bind_s('', ldap.sasl.gssapi(), sasl_flags=ldap.SASL_INTERACTIVE)
SASL/GSSAPI authentication started
[21038] 1554474723.505792: ccselect module realm chose cache KEYRING:persistent:0:0 with client principal admin@IPA.EXAMPLE for server principal ldap/master.ipa.example@IPA.EXAMPLE
[21038] 1554474723.505793: Getting credentials admin@IPA.EXAMPLE -> ldap/master.ipa.example@IPA.EXAMPLE using ccache KEYRING:persistent:0:0
[21038] 1554474723.505794: Retrieving admin@IPA.EXAMPLE -> ldap/master.ipa.example@IPA.EXAMPLE from KEYRING:persistent:0:0 with result: 0/Success
[21038] 1554474723.505796: Creating authenticator for admin@IPA.EXAMPLE -> ldap/master.ipa.example@IPA.EXAMPLE, seqnum 595174659, subkey aes256-cts/3C22, session key aes256-cts/8D66
[21038] 1554474723.505801: Read AP-REP, time 1554474723.505797, subkey aes256-cts/F9FE, seqnum 863878286
SASL username: admin@IPA.EXAMPLE
SASL SSF: 256
SASL data security layer installed.
0
>>> l.whoami_s()
'dn: uid=admin,cn=users,cn=accounts,dc=ipa,dc=example'
```

**Comment by JonathonReinhart** [comment]
@tiran Thanks for your quick reply!

> Is your libldap linked against MIT or Heimdal Kerberos?

Neither? I'm using MIT kerberos. [`libsasl2-modules-gssapi-mit`](https://packages.debian.org/buster/libsasl2-modules-gssapi-mit) is the package which enabled my simple `ldapsearch -Y GSSAPI` test to work.
```
$ apt list --installed 2>/dev/null  | grep -e ldap -e sasl -e krb -e kerberos -e cyrus
krb5-config/testing,now 2.6 all [installed,automatic]
krb5-locales/testing,now 1.17-2 all [installed]
krb5-multidev/testing,now 1.17-2 amd64 [installed,automatic]
krb5-user/testing,now 1.17-2 amd64 [installed]
ldap-utils/testing,now 2.4.47+dfsg-3 amd64 [installed]
libgssapi-krb5-2/testing,now 1.17-2 amd64 [installed,automatic]
libkrb5-3/testing,now 1.17-2 amd64 [installed,automatic]
libkrb5-dev/testing,now 1.17-2 amd64 [installed]
libkrb5support0/testing,now 1.17-2 amd64 [installed,automatic]
libldap-2.4-2/testing,now 2.4.47+dfsg-3 amd64 [installed,automatic]
libldap-common/testing,now 2.4.47+dfsg-3 all [installed,automatic]
libldap2-dev/testing,now 2.4.47+dfsg-3 amd64 [installed]
libpam-krb5/testing,now 4.8-2 amd64 [installed]
libsasl2-2/testing,now 2.1.27+dfsg-1 amd64 [installed,automatic]
libsasl2-dev/testing,now 2.1.27+dfsg-1 amd64 [installed]
libsasl2-modules-db/testing,now 2.1.27+dfsg-1 amd64 [installed,automatic]
libsasl2-modules-gssapi-mit/testing,now 2.1.27+dfsg-1 amd64 [installed]
libsasl2-modules/testing,now 2.1.27+dfsg-1 amd64 [installed,automatic]
sasl2-bin/testing,now 2.1.27+dfsg-1 amd64 [installed]
```



Here's the krb5 trace portion of the output:
```
SASL/GSSAPI authentication started
[26682] 1554523640.326713: ccselect module realm chose cache FILE:/tmp/krb5cc_3000020 with client principal someone@AD.EXAMPLE.COM for server principal ldap/samba-dc.ad.example.com@AD.EXAMPLE.COM
[26682] 1554523640.326714: Getting credentials someone@AD.EXAMPLE.COM -> ldap/samba-dc.ad.example.com@ using ccache FILE:/tmp/krb5cc_3000020
[26682] 1554523640.326715: Retrieving someone@AD.EXAMPLE.COM -> ldap/samba-dc.ad.example.com@ from FILE:/tmp/krb5cc_3000020 with result: 0/Success
[26682] 1554523640.326717: Creating authenticator for someone@AD.EXAMPLE.COM -> ldap/samba-dc.ad.example.com@, seqnum 902389607, subkey aes256-cts/FCF9, session key aes256-cts/62F6
[26682] 1554523640.326722: Read AP-REP, time 1554523640.326718, subkey aes256-cts/365E, seqnum 135569702
SASL username: someone@AD.EXAMPLE.COM
SASL SSF: 256 
SASL data security layer installed.
```

That trace looks the same as yours, and the same as when I run `ldapsearch -Y GSSAPI`

Here's the full log: [`python-ldap-gssapi-bind-error-with-krb5trace.txt`](https://github.com/python-ldap/python-ldap/files/3050134/python-ldap-gssapi-bind-error-with-krb5trace.txt)

**Comment by JonathonReinhart** [comment]
Here's a bit of a surprise: This also happens with a simple bind over TLS:

```python
import ldap,ldap.sasl
from pprint import pprint
from getpass import getpass

l = ldap.initialize("ldap://samba-dc.ad.example.com", trace_level=100)

ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)  # XXX HACK
l.start_tls_s()

who = input("Bind User DN:")
cred = getpass()
l.simple_bind_s(who, cred)

base = "dc=ad,dc=example,dc=com"
criteria = "(objectClass=user)"
result = l.search_s(base, ldap.SCOPE_SUBTREE, criteria)
pprint(result)
```
```
ldap.OPERATIONS_ERROR: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}
```

**Comment by JonathonReinhart** [comment]
Further strangeness:  I discovered (by pure luck) that if I call `search()` (async) prior to `search_s()` (sync), the sync call will succeed!

```python
#!/usr/bin/env python3
import ldap
from pprint import pprint

uri = 'ldap://samba-dc.ad.example.com'
base = 'dc=ad,dc=example,dc=com'

l = ldap.initialize(uri)
l.sasl_gssapi_bind_s()

def try_sync(i):
    print()
    try:
        r = l.search_s(base, ldap.SCOPE_SUBTREE, 'objectClass=person', ['name'])
    except ldap.OPERATIONS_ERROR as e:
        print("[{}] search_s() failed: {}".format(i, e))
    else:
        print("[{}] search_s() result:".format(i))
        pprint(r)


def try_async(i, wait=True):
    print()
    msgid = l.search(base, ldap.SCOPE_SUBTREE, 'objectClass=person', ['name'])
    print("[{}] search() returned msgid={}".format(i, msgid))

    if not wait:
        print("[{}] not waiting for result".format(i))
        return

    try:
        r = l.result(msgid)
    except ldap.OPERATIONS_ERROR as e:
        print("[{}] result({}) failed: {}".format(i, msgid, e))
    else:
        print("[{}] result() result:".format(i))
        pprint(r)



# [1] First try a synchronous search
try_sync(1)                 # Fail

# [2] First try an async search
try_async(2)                # Fail

# [3] Try a synchronous search again
try_sync(3)                 # Fail

# [4] Start an async search, but don't wait for the result. Then try sync.
try_async(4, False)
try_sync(4)                 # !!! This will work !!!

# [5] Try a synchronous search again
try_sync(5)                 # Fail

# [6] Try an async search again
try_async(6)                # Fail
```

Output:
```
$ ./ldaptest-1.py 

[1] search_s() failed: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}

[2] search() returned msgid=10
[2] result(10) failed: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}

[3] search_s() failed: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}

[4] search() returned msgid=22
[4] not waiting for result

[4] search_s() result:
[('CN=Administrator,CN=Users,DC=ad,DC=example,DC=com',
  {'name': [b'Administrator']}),
 ('CN=SAMBA-DC,OU=Domain Controllers,DC=ad,DC=example,DC=com',
  {'name': [b'SAMBA-DC']}),
 ('CN=Jonathon Reinhart,CN=Users,DC=ad,DC=example,DC=com',
  {'name': [b'Jonathon Reinhart']}),
 ('CN=WIN7-PC,CN=Computers,DC=ad,DC=example,DC=com',
  {'name': [b'WIN7-PC']}),
 ('CN=Guest,CN=Users,DC=ad,DC=example,DC=com', {'name': [b'Guest']}),
 ('CN=krbtgt,CN=Users,DC=ad,DC=example,DC=com', {'name': [b'krbtgt']}),
 (None, ['ldap://ad.example.com/CN=Configuration,DC=ad,DC=example,DC=com']),
 (None,
  ['ldap://ad.example.com/DC=DomainDnsZones,DC=ad,DC=example,DC=com']),
 (None,
  ['ldap://ad.example.com/DC=ForestDnsZones,DC=ad,DC=example,DC=com'])]

[5] search_s() failed: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}

[6] search() returned msgid=35
[6] result(35) failed: {'desc': 'Operations error', 'info': '00002020: Operation unavailable without authentication'}
```

It appears to be a race condition because one time (out of dozens) that I ran this script, step `[4]` actually failed.

This behavior is consistent on two systems, both authenticating as the same user:
- Debian buster (on the DC itself):
  - Python version  3.7.3rc1
  - `python-ldap` version 3.1.0
- Fedora 28 client system
  - Python version 3.6.8
  - `python-ldap` version 3.1.0
  - ```
    $ dnf list installed | grep -e ldap -e krb -e kerbreos -e gss -e sasl
    cyrus-sasl.x86_64                          2.1.27-0.2rc7.fc28           @updates
    cyrus-sasl-gssapi.x86_64                   2.1.27-0.2rc7.fc28           @updates
    cyrus-sasl-lib.x86_64                      2.1.27-0.2rc7.fc28           @updates
    cyrus-sasl-md5.x86_64                      2.1.27-0.2rc7.fc28           @updates
    cyrus-sasl-plain.x86_64                    2.1.27-0.2rc7.fc28           @updates
    cyrus-sasl-scram.x86_64                    2.1.27-0.2rc7.fc28           @updates
    gssdp.x86_64                               1.0.2-5.fc28                 @fedora 
    gssproxy.x86_64                            0.8.0-4.fc28                 @fedora 
    krb5-devel.x86_64                          1.16.1-25.fc28               @updates
    krb5-libs.i686                             1.16.1-25.fc28               @updates
    krb5-libs.x86_64                           1.16.1-25.fc28               @updates
    krb5-workstation.x86_64                    1.16.1-25.fc28               @updates
    ldapvi.x86_64                              1.7-29.fc28                  @fedora 
    openldap.x86_64                            2.4.46-5.fc28                @updates
    openldap-clients.x86_64                    2.4.46-5.fc28                @updates
    pam_krb5.x86_64                            2.4.13-9.fc28                @fedora 
    php-ldap.x86_64                            7.2.16-1.fc28                @updates
    python2-krbv.x86_64                        1.0.90-18.fc28               @fedora 
    python3-ldap.x86_64                        3.1.0-1.fc28                 @updates
    sssd-krb5.x86_64                           1.16.3-2.fc28                @updates
    sssd-krb5-common.x86_64                    1.16.3-2.fc28                @updates
    sssd-ldap.x86_64                           1.16.3-2.fc28                @updates
    ```

**Comment by JonathonReinhart** [comment]
I'm becoming more convinced that this is a bug in `python-ldap`. Not only does `ldapsearch` work correctly, but so does this PHP script (using `php-ldap` installed from the distro repos):
```php
#!/usr/bin/env php
<?php
    echo "Hello, world!\n";

    $uri = 'ldap://samba-dc.ad.example.com';
    $base = 'dc=ad,dc=example,dc=com';
    $criteria = '(objectClass=user)';


    $l = ldap_connect($uri) or die("ldap_connect() failed");
    ldap_set_option($l, LDAP_OPT_PROTOCOL_VERSION, 3);
    ldap_set_option($l, LDAP_OPT_REFERRALS, false);

    ldap_sasl_bind($l, NULL, NULL, 'GSSAPI') or die("ldap_sasl_bind() failed");

    $search = ldap_search($l, $base, $criteria) or die("ldap_search() failed");

    $entries = ldap_get_entries($l, $search) or die("ldap_get_entries() failed");
    var_dump($entries);
?>
```

**Comment by JonathonReinhart** [comment]
The saga continues. I've found three ways to get the code to "work":
- Disable referrals
- Further constrain the base DN (e.g. to `CN=Users`)
- Start an async search and ignore the msgid (as shown above: https://github.com/python-ldap/python-ldap/issues/275#issuecomment-480517622)

```python
import ldap
from pprint import pprint

# Setting any one of these to True will lead to a valid result
test_disable_referrals  = False
test_constrain_base     = False
test_ignore_sync_search = False


# Let's go
l = ldap.initialize("ldap://samba-dc.ad.example.com")

base = ['dc=ad', 'dc=example', 'dc=com']
criteria = "(objectClass=user)"
attrs = ['name']

if test_disable_referrals:
    l.set_option(ldap.OPT_REFERRALS, 0)

rc = l.sasl_gssapi_bind_s()

if test_constrain_base:
    base.insert(0, 'cn=users')

if test_ignore_sync_search:
    msgid = l.search(','.join(base), ldap.SCOPE_SUBTREE, criteria, attrs)
    # ignore msgid

result = l.search_s(','.join(base), ldap.SCOPE_SUBTREE, criteria, attrs)
pprint(result)
```

**Comment by tiran** [comment]
It's most likely referrals. python-ldap leaves the ``OPT_REFERRALS`` option in its default state. ldapsearch disables referrals by default:

https://github.com/openldap/openldap/blob/593512bb7b2b5d23a658d3a8d05bdeeb15d7611f/clients/tools/common.c#L66
https://github.com/openldap/openldap/blob/593512bb7b2b5d23a658d3a8d05bdeeb15d7611f/clients/tools/common.c#L1420-L1426

You can use the undocumented option ``-C`` to enabled referrals in ``ldapsearch`.

**Comment by JonathonReinhart** [comment]
Indeed, passing `-C` causes a similar error:
```
$ diff ldapsearch-default.txt ldapsearch-enable-referrals.txt 
48c48,49
< result: 0 Success
---
> result: 1 Operations error
> text: 00002020: Operation unavailable without authentication
```
---
It looks like MS AD returns this error string:
> In order to perform this operation a successful bind must be completed on the connection.

While Samba AD returns:
> Operation unavailable without authentication

https://github.com/samba-team/samba/blob/samba-4.9.4/source4/dsdb/samdb/ldb_modules/rootdse.c#L755-L756

Without digging too hard into the samba code, the fact that this error happens in `rootdse.c` might also explain why constraining to `CN=users` made the problem also go away.

This error message difference is what made this problem more difficult for me to track down. Otherwise I would have landed [at this question on the FAQ](https://www.python-ldap.org/en/python-ldap-3.2.0/faq.html?highlight=referral).

Perhaps I should submit a PR to add the Samba message to the FAQ as well?

**Comment by JonathonReinhart** [comment]
This issue can probably be closed. The only lingering thing is the behavior of `test_ignore_async_search` test above. It was very surprising that an abandoned async search would change how a subsequent search behaved. If that is not interesting to you, feel free to close. Thanks for your help!

**Comment by tiran** [comment]
The updated FAQ has landed a year ago. Closing.

Thanks!
