### ISSUE TITLE
ldapurl parsing fails when scheme is uppercase

### ISSUE THREAD

**Issue by dmulder** [python-ldap/python-ldap#280]
https://github.com/python-ldap/python-ldap/blob/adf9dc402380572b1d3b5bc6fa1d353bbed35074/Lib/ldapurl.py#L260

This only checks lower case instances of ldap, ldaps, and ldapi. What if they are upper case?

**Comment by tiran** [comment]
RFC 1738 defines the schema of an uniformed resource locator as a sequence of characters from the set ``a-z0-9+.-``. ``LDAP://host`` is not a valid URL schema identifier. RFC 1738 also suggests that applications should treat upper case schema like lower case schema. The RFC uses the word *should*, not *must*, so it's not a requirement but an optional feature.

I'm -0 on the change and let Petr decide. I have been working with LDAP for almost a decade and never ran into a situation with an upper case scheme. The change also needs tests and a thorough review of the code base.

**Comment by encukou** [comment]
I'm +0 – this is very unlikely to break existing code, and *should* features are nice to have.

**Comment by quanah** [comment]
Reading [RFC2119](https://www.ietf.org/rfc/rfc2119.txt), I'm not entirely sure I agree with your definition of should.

**Comment by quanah** [comment]
I would also note that OpenLDAP (which strives for being as RFC compliant as possible) accepts uppercase URI schemes:

```
ldapwhoami -x -H LDAP:// -D "cn=Marice McCaugherty,ou=Product Testing,dc=example,dc=com" -w secret
dn:cn=Marice McCaugherty,ou=Product Testing,dc=example,dc=com
```

This would generally indicate to me that it is more correct to accept both upper and lower case format for the URI scheme.
