### ISSUE TITLE
modifyModlist converting strings in values to list of characters

### ISSUE THREAD

**Issue by ConnorRules** [python-ldap/python-ldap#286]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
In modlist.py the function modifyModlist will convert any string in the new value to a list of characters per the following line:
  ` new_value = [item for item in value if item is not None]`

Steps to reproduce: 

Calling the function like so:

`modifyModlist({'memberUid': '2001','description': ''},{'memberUid': []    ,'description': "NEWDESC"})`

will produce the modlist:

`[('MOD_DELETE', 'memberUid', None), ('MOD_ADD', 'description', ['N', 'E', 'W', 'D', 'E', 'S', 'C'])]`

Operating system: 

Python version: 3.6

python-ldap version: 3.2

**Comment by ConnorRules** [comment]
Looks like that's intended. I need to dig further as to why my stuff is breaking :(

**Comment by nrother** [comment]
I was also recently hit by this issue. Are you sure it is intended this way? The change was introduced by 17b4000. For me it looks like the author of the commit simply forgot about the fact that strings are iterable in python.

**Comment by dunatotatos** [comment]
IMHO, this should be re-open. If it's intended, the intention probably needs to be re-evaluated.

**Comment by tiran** [comment]
The functions behave as designed. In python-ldap entry attributes are always dict's of text keys to list of bytes. There are no checks for invalid types or fallbacks that convert a str/bytes object into a single-item list.
