### ISSUE TITLE
ReconnectLDAPObject does not reconnect in search_ext()

### ISSUE THREAD

**Issue by spaceone** [python-ldap/python-ldap#294]
`ldap.ldapobject.ReconnectLDAPObject` does not overwrite `search_ext` but only `search_ext_s`.
Is there a reason for this? Is it discouraged?

Otherwise it should be possible to use code like this?:
`lo._apply_method_s(SimpleLDAPObject.result3, lo._apply_method_s(SimpleLDAPObject.search_ext, *args, **kwargs))`

I want the result of a serverctrl and am aware that the control might be invalid if there is a reconnection during the search.

**Comment by mistotebe** [comment]
My take on this is that if you don't use the `_s` functions, you could have more than one request pending to restart, so it's only done when it already has exclusive control of the connection.

**Comment by spaceone** [comment]
Thanks, closing this issue as nothing can be done about it.
