### ISSUE TITLE
ldap.dn.str2dn('cn=foo\\?,dc=base')

### ISSUE THREAD

**Issue by spaceone** [python-ldap/python-ldap#296]
An ldap search in a Samba 4 LDAP directory returns DN's containing a `?` escaped as `\?`.
This fails to get parsed:
```python
>>> import ldap.dn
>>> ldap.dn.str2dn('cn=foo\\?,dc=base')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ldap/dn.py", line 53, in str2dn
    return ldap.functions._ldap_function_call(None,_ldap.str2dn,dn,flags)
  File "/usr/lib/python2.7/dist-packages/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.DECODING_ERROR
```

As a workaround I am using a function like:
```python
def str2dn(dn):
       try:
               return ldap.dn.str2dn(dn)
       except ldap.DECODING_ERROR:
               return ldap.dn.str2dn(dn.replace('\\?', '?'))
```

Just wanted to let you know. I am unsure If this is an error in the Samba 4 LDAP implementation or if this is acutally allowed LDAP syntax.

**Comment by spaceone** [comment]
Maybe related to: https://github.com/python-ldap/python-ldap/issues/257

**Comment by quanah** [comment]
I would compare vs OpenLDAP's behavior with a similar DN.

**Comment by tiran** [comment]
Please report this bug with OpenLDAP. python-ldap uses libldap's ``ldap_bv2dn()`` to parse the string.

**Comment by spaceone** [comment]
I created a bug at Samba: https://bugzilla.samba.org/show_bug.cgi?id=14073
