### ISSUE TITLE
Cant pip python-ldap on 3.6 

### ISSUE THREAD

**Issue by pcamera123** [python-ldap/python-ldap#297]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

Im running in a docker env, single app single python instance 3.6  I cant deploy python-ldap in python3.6 env 

# Use the Python3.6 image
FROM python:3.6

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install the dependencies
RUN pip3 install -r requirements.txt

# run the command to start uWSGI
CMD ["uwsgi", "app.ini"]

Issue description:

  Running setup.py install for python-ldap: started
    Running setup.py install for python-ldap: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ni8_pla_/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ni8_pla_/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gma0a6c1/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-ni8_pla_/python-ldap/
    Complete output (81 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.6
    copying Lib/ldif.py -> build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.6/ldap
    copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.6/ldap
    creating build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.6/ldap/controls
    copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.6/ldap/controls
    creating build/lib.linux-x86_64-3.6/ldap/extop
    copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.6/ldap/extop
    copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.6/ldap/extop
    creating build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.6/ldap/schema
    copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.6/ldap/schema
    creating build/lib.linux-x86_64-3.6/slapdtest
    copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.6/slapdtest
    copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.6/slapdtest
    running egg_info
    writing Lib/python_ldap.egg-info/PKG-INFO
    writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
    writing requirements to Lib/python_ldap.egg-info/requires.txt
    writing top-level names to Lib/python_ldap.egg-info/top_level.txt
    reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc/.build'
    writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.6/slapdtest/certs
    copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.6/slapdtest/certs
    running build_ext
    building '_ldap' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/Modules
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.2.0 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:8:
    Modules/constants.h:7:10: fatal error: lber.h: No such file or directory
     #include "lber.h"
              ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ni8_pla_/python-ldap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ni8_pla_/python-ldap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gma0a6c1/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
ERROR: Service 'flask' failed to build: The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

i followed what was recommended in the following and no change 

https://stackoverflow.com/questions/4768446/i-cant-install-python-ldap

when I try to pip before launching docker-compose it clearly shows its installed 

(env) root@pdc-mgmt-netauto:/home/administrator/app/flask# pip install python-ldap
Requirement already satisfied: python-ldap in ./env/lib/python3.6/site-packages (3.2.0)
Requirement already satisfied: pyasn1>=0.3.7 in ./env/lib/python3.6/site-packages (from python-ldap) (0.4.6)
Requirement already satisfied: pyasn1_modules>=0.1.5 in ./env/lib/python3.6/site-packages (from python-ldap) (0.2.6)

also lber.h is also installed 

(env) root@pdc-mgmt-netauto:/home/administrator/app/flask# apt-file search lber.h
golang-openldap-dev: /usr/share/gocode/src/github.com/mqu/openldap/_docs/include/lber.h
libldap2-dev: /usr/include/lber.h

Operating system: 
Ubuntu 18.04

Python version: 
(env) root@pdc-mgmt-netauto:/home/administrator/app/flask# python -V
Python 3.6.8

python-ldap version: 

python-ldap 3.2.0
Think thats what its getting, should be pulling the dependency for flask-simpleldap 
not sure how too check

**Comment by tiran** [comment]
You are missing the OpenLDAP development headers and libraries. Please follow the [documentation](https://www.python-ldap.org/en/python-ldap-3.2.0/installing.html#debian) for installation from source.

**Comment by quanah** [comment]
> 
> 
> You are missing the OpenLDAP development headers and libraries. Please follow the [documentation](https://www.python-ldap.org/en/python-ldap-3.2.0/installing.html#debian) for installation from source.
 
Really? Because their response shows they have the libldap2-dev package installed:

> libldap2-dev: /usr/include/lber.h

**Comment by quanah** [comment]
More specifically:

```
apt show libldap2-dev
Package: libldap2-dev
Version: 2.4.45+dfsg-1ubuntu1.3
Priority: extra
Section: libdevel
Source: openldap
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1,470 kB
Provides: libldap-dev
Depends: libldap-2.4-2 (= 2.4.45+dfsg-1ubuntu1.3)
Conflicts: libldap-dev, libopenldap-dev
Replaces: libopenldap-dev
Homepage: http://www.openldap.org/
Supported: 5y
Download-Size: 261 kB
APT-Sources: http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
Description: OpenLDAP development libraries
 This package allows development of LDAP applications using the OpenLDAP
 libraries. It includes headers, libraries and links to allow static and
 dynamic linking.
```

**Comment by quanah** [comment]
Bah, never mind, apt-file searches all packages, installed or not. ;) Sorry for the noise.

**Comment by pcamera123** [comment]
not sure what im doing wrong here i have all of this installed

root@pdc-mgmt-netauto:/home/administrator/app/flask# apt-get install
build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils
python-tox lcov valgrind
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libsasl2-dev is already the newest version
(2.1.27~101-g0780600+dfsg-3ubuntu2).
lcov is already the newest version (1.13-3).
python-tox is already the newest version (2.5.0-1).
ldap-utils is already the newest version (2.4.45+dfsg-1ubuntu1.3).
libldap2-dev is already the newest version (2.4.45+dfsg-1ubuntu1.3).
python3-dev is already the newest version (3.6.7-1~18.04).
slapd is already the newest version (2.4.45+dfsg-1ubuntu1.3).
valgrind is already the newest version (1:3.13.0-2ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

still getting failed docker build

**Comment by epiczain1234** [comment]
try:
ARCHFLAGS="-arch x86_64" pip3 install python-ldap
