### ISSUE TITLE
ValueError exception trying to set_option OPT_X_TLS_CACERTFILE in Mac OS

### ISSUE THREAD

**Issue by shubb30** [python-ldap/python-ldap#301]
Mac OS 10.14.6
Python 3.7.2
python-ldap 3.2.0
---
Issue description:

On Mac OS, trying to set the `OPT_X_TLS_CACERTFILE` option raises a ValueError.

Steps to reproduce: 

```
$ python
Python 3.7.2 (default, Feb 12 2019, 08:16:38)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> l = ldap.initialize("ldaps://server")
>>> l.set_option(ldap.OPT_X_TLS_CACERTFILE, "/path/to/file")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 921, in set_option
    return self._ldap_call(self._l.set_option,option,invalue)
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ValueError: option error
>>>
```

Doing the same thing in a Docker container running Python 3.7.3 does not have the problem.

```
# python
Python 3.7.3 (default, Mar 27 2019, 23:51:31)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> l = ldap.initialize("ldaps://server")
>>> l.set_option(ldap.OPT_X_TLS_CACERTFILE, "/path/to/file")
>>>
```

**Comment by jfarshankar** [comment]
The openldap which comes bundled with OSX seems to be the issue. Based on the instructions here(https://stackoverflow.com/a/43450931)  I tried using homebrew to install openldap and then building the package with that, but I could not get it to work. Finally i tried installing python-ldap with conda and it just worked.

**Comment by quanah** [comment]
The OSX version of OpenLDAP is hacked to build against a custom Apple written TLS library.  I don't know what option(s) it allows for the TLS CA certificate to be set.

**Comment by quanah** [comment]
Per the Apple written man page, it looks like ldap.conf wants "TLS_TRUSTED_CERTS" to be set, so I'm guessing they have an analogous option for setting this directly as well.  You'd need to track down their source tree to discover exactly what they named it.

**Comment by sara1068** [comment]
> The openldap which comes bundled with OSX seems to be the issue. Based on the instructions here(https://stackoverflow.com/a/43450931) I tried using homebrew to install openldap and then building the package with that, but I could not get it to work. Finally i tried installing python-ldap with conda and it just worked.

Got my program to accept the certificate (although just a start), after debugging for hours. Thanks a lot

**Comment by quanah** [comment]
If you got it working using the native OSX ldap libraries, it would be nice if you could document how :)
