### ISSUE TITLE
Example in documentation does not work

### ISSUE THREAD

**Issue by robert-sherwood** [python-ldap/python-ldap#306]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
Example at the following link:
https://github.com/python-ldap/python-ldap/blob/master/Doc/reference/ldif.rst#example

>>> import sys,ldif
>>> entry={'objectClass':['top','person'],'cn':['Michael Stroeder'],'sn':['Stroeder']}
>>> dn='cn=Michael Stroeder,ou=Test'
>>> ldif_writer=ldif.LDIFWriter(sys.stdout)
>>> ldif_writer.unparse(dn,entry)

When entering this code in the python console, the following error is received:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/plainid/PycharmProjects/LDIF_Generator/venv/lib/python3.7/site-packages/ldif.py", line 198, in unparse
    self._unparseEntryRecord(record)
  File "/Users/plainid/PycharmProjects/LDIF_Generator/venv/lib/python3.7/site-packages/ldif.py", line 155, in _unparseEntryRecord
    self._unparseAttrTypeandValue(attr_type,attr_value)
  File "/Users/plainid/PycharmProjects/LDIF_Generator/venv/lib/python3.7/site-packages/ldif.py", line 139, in _unparseAttrTypeandValue
    if self._needs_base64_encoding(attr_type,attr_value):
  File "/Users/plainid/PycharmProjects/LDIF_Generator/venv/lib/python3.7/site-packages/ldif.py", line 128, in _needs_base64_encoding
    not safe_string_re.search(attr_value) is None
TypeError: cannot use a bytes pattern on a string-like object

Steps to reproduce: 
Enter example from documentation in python console

Fix is simple, mark the entry attribute strings as bytestrings:
entry={"objectClass":[b"top",b"person"],"cn":[b"Michael Stroeder"],"sn":[b"Stroeder"]}

Operating system: 
Mac OS
Python version: 
3.7
python-ldap version: 
3.2.0

**Comment by atterdag** [comment]
Its not just python 3.7, I have the exact same issue with Python 3.6.8 on Ubuntu 18.04

**Comment by atterdag** [comment]
Its kinda easy to solve in ldif.py. Of course this is a bit of a hack, but it works:

```
diff --git a/Lib/ldif.py b/Lib/ldif.py
index a26c8ac..2d12b10 100644
--- a/Lib/ldif.py
+++ b/Lib/ldif.py
@@ -124,6 +124,8 @@ class LDIFWriter:
     returns 1 if attr_value has to be base-64 encoded because
     of special chars or because attr_type is in self._base64_attrs
     """
+    if isinstance(attr_value, str):
+      attr_value = str.encode(attr_value)
     return attr_type.lower() in self._base64_attrs or \
            not safe_string_re.search(attr_value) is None

@@ -142,7 +144,9 @@ class LDIFWriter:
       encoded = encoded.replace('\n','')
       self._unfold_lines(':: '.join([attr_type, encoded]))
     else:
-      self._unfold_lines(': '.join([attr_type, attr_value.decode('ascii')]))
+      if isinstance(attr_value, bytes):
+        attr_value = attr_value.decode('ascii')
+      self._unfold_lines(': '.join([attr_type, attr_value]))
     return # _unparseAttrTypeandValue()

   def _unparseEntryRecord(self,entry):
```
