### ISSUE TITLE
Cannot connect to LDAP server with TLS SNI

### ISSUE THREAD

**Issue by sebthom** [python-ldap/python-ldap#314]
I am trying to configure https://github.com/nginxinc/nginx-ldap-auth to work with an LDAP server who's TLS endpoint uses SNI (Server Name Indication). Connecting to an LDAP server via TLS without SNI works.

During connection the following error is shown
> Error while binding as search user: {'info': u'error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error', 'desc': u"Can't contact LDAP server"}, server="ldaps://ldap.server.local:636", login="testuser"

Python version: Python 2.7.16
python-ldap version:  python_ldap-3.2.0

Is there a configuration option in python-ldap that needs to be set to enable SNI support or is this a bug?

**Comment by tiran** [comment]
TLS layer is handled by OpenLDAP. There is no flag to set a SNI name with [ldap_set_option](https://linux.die.net/man/3/ldap_get_option). I don't see any call to ``SSL_set_tlsext_host_name`` in OpenLDAP code, too.

Please report the bug with OpenLDAP. There is nothing we can do from python-ldap code. Sorry.

**Comment by sebthom** [comment]
Thanks for your quick response.
