### ISSUE TITLE
After pip installation, import fails on faulty print statement

### ISSUE THREAD

**Issue by zurovec** [python-ldap/python-ldap#319]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
After PIP installation of python-ldap, version 3.2.0, the module gives an error on import. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leonard/anaconda3/lib/python3.6/site-packages/flask_ldap/__init__.py", line 90
    print self.app.config['LDAP_HOST']
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.app.config['LDAP_HOST'])?

Steps to reproduce: 
pip install python-ldap

python
import flask-ldap

error report:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leonard/anaconda3/lib/python3.6/site-packages/flask_ldap/__init__.py", line 90
    print self.app.config['LDAP_HOST']
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.app.config['LDAP_HOST'])?

Operating system: linux ubuntu 18.04.3 LTS and on macOS 10.14.6 Mojave

Python version: 3.6

python-ldap version: 3.2.0

**Comment by encukou** [comment]
> File "/Users/leonard/anaconda3/lib/python3.6/site-packages/flask_ldap/\_\_init\_\_.py", line 90

This error appears to be in `flask_ldap`, not `python_ldap`.

**Comment by tiran** [comment]
``flask_ldap`` is a 3rd party module and not maintained by us.

The last release of https://pypi.org/project/Flask-LDAP/ was in 2014. I guess the package was never ported to Python 3.

**Comment by zurovec** [comment]
ah my bad i'm in the wrong repo! I will close it
