### ISSUE TITLE
Simple bind fails when LDAP user is using sha512

### ISSUE THREAD

**Issue by msimonelli331** [python-ldap/python-ldap#321]
Issue description:
Using simple_bind_s fails with Invalid credentials when a more secure hash is being used. The same exact credentials work when a less secure hash, like md5 is used.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 446, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 751, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 758, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_CREDENTIALS: {'desc': 'Invalid credentials', 'info': '80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580'}`

I can login using AD Explorer but when I try with python-ldap it fails. It only works when I change the hash.

Steps to reproduce: 
Create a user on an LDAP server, create a password with MD5, use python-ldap to bind. That should work. Now change the users password hash to sha512. Use the same code to bind. That will fail saying Invalid credentials (data 52e) meaning the password is wrong

Operating system: 
Alpine Linux

Python version: 
Python 3.6

python-ldap version: 
Name: python-ldap
Version: 3.2.0

**Comment by quanah** [comment]
What LDAP server?
How are you "changing" to an sha512 hash for the user password?

**Comment by msimonelli331** [comment]
I'm using osixia/openldap:1.2.4 container and I use osixia/phpldapadmin:0.8.0 to manage it. I can edit my users password through the admin console. Below is what it looks like when I go from md5 (or any other hash) to sha512. I updated my title to only mention sha512 because that's the only one failing right now. This is how I'm testing the issue but my real issue is when I try connecting to my works LDAP. I don't actually know what hash they're using but I'm sure it's something like sha512 and is the reason it's failing. However I cannot test that LDAP server because I am not an admin for it.

`>>> l.simple_bind_s("cn=me,ou=people,dc=domain,dc=com", "password")
(97, [], 6, [])
>>> l.simple_bind_s("cn=me,ou=people,dc=domain,dc=com", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 446, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 751, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 758, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3.6/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
`

**Comment by msimonelli331** [comment]
After further testing this seems to be an issue with every ldap client. openldap-clients ldapsearch has the issue and the other python library ldap3 has the issue.

**Comment by quanah** [comment]
A couple of things:

a) The server actually has to have SHA512 support, since that's not part of the LDAP RFC specifications.  OpenLDAP does have a pw-sha2 module that allows support for SHA512, SSHA512, etc.  However, it is important to know how that is being pushed to the LDAP server.

The correct method requires (a) that the module is loaded and instantiated on the database, (b) generally that SSHA512 (or whatever) has been set as the default hash type, and (c) that an LDAPv3 password modification is used.

If the client side is doing a direct replace operation on the userPassword attribute (which should not be done, but often client side software is poorly written), then whatever hash the client generated may or may not work.  And again, it still requires that the server be configured to support such hashes.  I've had zero issues with python-ldap interacting with SSHA512 hashed passwords when proper procedures are in place.

**Comment by quanah** [comment]
At a minimum, you need to confirm that (a) PHPLDAPAdmin does the right thing (an ldap v3 password modification operation), (b) that your Osixia ldap container is configured to both load and use the pw-sha2 module, and (c) that SSHA512 or similar is set to be the default password hash.

**Comment by tiran** [comment]
I'm closing this issue as there has been no response from @msimonelli331  for a couple of months. It doesn't look like a problem with python-ldap either. Passwords are verified on the server side and your server is refusing the password.

Thank you @quanah for your assistance!
