### ISSUE TITLE
search_ext does not allow top level domain searches

### ISSUE THREAD

**Issue by levensailor** [python-ldap/python-ldap#322]
currently I users in multiple OUs and allowing a search of the DC=domain,DC=com would allow me to not have to rewrite code to allow multiple searches and for all the OUs I have.

**Comment by tiran** [comment]
@levensailor could you please give us an example which query you want to use?

python-ldap doesn't limit search scope or search base. It calls into OpenLDAP's libldap for search operations. Any kind of limitation either come from libldap, your server, or the LDAP protocol in general.

**Comment by mistotebe** [comment]
Closing due to no response, feel free to reopen.
