### ISSUE TITLE
modify_s cannot modify gecos attribute en Debian buster

### ISSUE THREAD

**Issue by manu5801** [python-ldap/python-ldap#324]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

When using python-ldap from a python2 script, I cannot modify the gecos attribute of any user.

---

Issue description:
I cannot use modify_s to modify any gecos attribute since I upgraded to Debian buster. I get an error message:
`ldap.CONSTRAINT_VIOLATION: {'info': u'gecos: multiple values provided', 'desc': u'Constraint violation'}
`

Steps to reproduce: 

Add the following with ldapadd:
`dn: ou=Users,dc=example,dc=com
objectClass: organizationalUnit
ou: Users

dn: cn=toto,ou=Users,dc=example,dc=com
cn: toto
objectClass: account
objectClass: posixAccount
loginShell: /bin/false
uidNumber: 10015
gidNumber: 10015
gecos: Jacques Toto (Jacques.Toto@example.com),,,
homeDirectory: /home/toto
uid: toto`

Then try to execute the following script with python2:
`import ldap
import ldap.modlist

pwd="***********"
dn = "cn=toto,ou=Users,dc=example,dc=com"
gecos_old = "Jacques Toto (Jacques.Toto@example.com),,,"
gecos_new = "Jack Toto (jack.toto@example.com),,,"

old={'gecos':gecos_old}
new={'gecos':gecos_new}

ldap_srv = ldap.initialize('ldap://localhost')
ldap_srv.simple_bind("cn=admin,dc=example,dc=com",pwd);
ldap_srv.modify_s(dn,ldap.modlist.modifyModlist(old,new))`

Operating system: 

Debian buster = the issue is there (python 2.7.16, python-ldap 3.1.0, slapd 2.4.47)
Debian stretch = The previous code works (python 2.7.13, python-ldap 2.4.28, slapd 2.4.44)

Python version: 2.7.16

python-ldap version: 3.1.0

**Comment by tiran** [comment]
Attribute values must be a list of bytes, not a single string.

Your example code creates a mod list like this:
```
>>> ldap.modlist.modifyModlist(old,new)
[(1, 'gecos', None), (0, 'gecos', ['J', 'a', 'c', 'k', ' ', 'T', 'o', 't', 'o', ' ', '(', 'j', 'a', 'c', 'k', '.', 't', 'o', 't', 'o', '@', 'e', 'x', 'a', 'm', 'p', 'l', 'e', '.', 'c', 'o', 'm', ')', ',', ',', ','])]
```

Try this:
```
>>> old = {'gecos': [b"Jacques Toto (Jacques.Toto@example.com),,,"]}
>>> new = {'gecos': [b"Jack Toto (jack.toto@example.com),,,"]}
>>> ldap.modlist.modifyModlist(old, new)
[(1, 'gecos', None), (0, 'gecos', [b'Jack Toto (jack.toto@example.com),,,'])]
```

**Comment by manu5801** [comment]
Thanks a lot it works now ! 
But how come did my buggy code work with older releases of python-ldap ?

**Comment by tiran** [comment]
You are welcome!
