### ISSUE TITLE
please deploy the latest also in PyPi

### ISSUE THREAD

**Issue by uzk-develop** [python-ldap/python-ldap#328]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
The file from Pypi : \python-ldap-3.2.0\Lib\ldap\__init__.py
still contains the python2 import thread in line 57

try:
  # Check if Python installation was build with thread support
  import thread
except ImportError:
  LDAPLockBaseClass = DummyLock
else:
  import threading
  LDAPLockBaseClass = threading.Lock

This issue was fixed in https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/__init__.py
whith the python 3 import threading in line 57 which works fine.
see. https://github.com/python-ldap/python-ldap/commit/95e1d1a8aa9e6aa036f085af1ace3c295e78412b#diff-24264d34dc2d10c612d785e4a52e95d5

try:
  # Check if Python installation was build with thread support
  import threading
except ImportError:
  LDAPLockBaseClass = DummyLock
else:
  LDAPLockBaseClass = threading.Lock

Would you be so kind to unify the two versions? Thanks.  

Steps to reproduce: 

Operating system: 

Python version: 

python-ldap version:

**Comment by encukou** [comment]
The latest release is, finally, [on PyPI](https://pypi.org/project/python-ldap/).
