### ISSUE TITLE
TypeError: ('Tuple_to_LDAPMod(): expected a byte string in the list', 'k')

### ISSUE THREAD

**Issue by ITslacker** [python-ldap/python-ldap#329]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
error message:

`Traceback (most recent call last):
  File "scripts/ext_jira_user_add.py", line 127, in <module>
    create_user()
  File "scripts/ext_jira_user_add.py", line 116, in create_user
    ldap_conn.add_s(dn, entry)
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 430, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 415, in add_ext_s
    msgid = self.add_ext(dn,modlist,serverctrls,clientctrls)
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 412, in add_ext
    return self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/local/lib/python3.7/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
TypeError: ('Tuple_to_LDAPMod(): expected a byte string in the list', 'k')`

piece of python script:

```#Creates new entry in LDAP for given user
def create_user():
    dn = user['username'] + ',' + LDAP_BASE_DN
    fullname = (user['firstname'] + " " + user['lastname'])
    entry = []
    entry.extend([
        ('objectClass', ["top".encode('utf-8)'), "person".encode('utf-8'), "organizationalPerson".encode('utf-8'), "inetOrgPerson".encode('utf-8'), "homeInfo".encode('utf-8')]),
        ('uid', user['username']),
        ('cn', fullname),
        ('givenname', user['firstname']),
        ('sn', user['lastname']),
        ('mail', user['email']),
        ('uidNumber', str(user['uid'])),
        ('userPassword', user['password']),
        ('securityEquals', "cn=jira,ou=Groups,o=External"),
        ('groupMembership', "cn=jira,ou=Groups,o=External")
    ])
    ldap_conn = ldap.initialize(LDAP_HOST)
    ldap_conn.simple_bind_s(LDAP_ADMIN_DN, admin_pass)
    try:
        ldap_conn.add_s(dn, entry)
    finally:
        ldap_conn.unbind_s()

### MAIN: call functions ###
admin_pass        = input_ldap_pass()
try_ldap_bind()

user              = input_data()
user['password']  = generate_password()
print("Creating LDAP entry")
create_user()

print("Account for user " + user['username'] + "successfuly created")
print("Initial password is: " + user['password'])```



Steps to reproduce: 



Operating system: 
MacOS 10.14.6
Python version: 
v. 3.7.7 64-bit
python-ldap version: 
v. 3.2.0

**Comment by tiran** [comment]
There are multiple issues in the code. Several entries are strings. All attribute values must be **list** of **bytes**, e.g. 

```
("uid", [user["username"].encode("utf-8")]),
```

**Comment by ITslacker** [comment]
thank you, that worked

**Comment by tiran** [comment]
You are welcome!
