### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [python-ldap/python-ldap#331]
Wheels (`.whl`) for this package are currently missing from PyPI. Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdsit bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by encukou** [comment]
This would require bundling OpenLDAP for various operating systems. I can't commit to keeping the wheels updated with the latest OpenLDAP security patches.

**Comment by johnthagen** [comment]
Ah, so a pure Python wheel isn't an option here due to system dependencies?

**Comment by tiran** [comment]
python-ldap is a wrapper for OpenLDAP's libldap and liblber. The libraries depend on MIT Kerberos or Heimdall Kerberos, GSSAPI, Cyrus SASL, OpenSSL, and their dependencies. The manylinux wheel standard doesn't cover these libraries. Static linking or ``auditwheel repair`` isn't an option that works well for these libraries.

**Comment by johnthagen** [comment]
👍 Got it. I'll close this issue then.
