### ISSUE TITLE
isLDAPUrl does not detect missing port

### ISSUE THREAD

**Issue by DoraPaula** [python-ldap/python-ldap#332]
Operating system: Debian bulleye
python-ldap version: https://packages.debian.org/bullseye/python3-ldap

Issue description:

Shouldn't the following code sample return "brokenLdapUrl is broken!"?

```
#!/usr/bin/python3

import ldap
import ldapurl

brokenLdapUrl = "ldap://ldap.example.com:/dc=example,dc=com?cn?sub?(&(uid=test)(objectclass=inetOrgPerson))"
if (not ldapurl.isLDAPUrl(brokenLdapUrl)):
    print ("brokenLdapUrl is broken!")
else:
    print ("brokenLdapUrl is fine, although the port is missing?")
print("")
```
Invalid port numbers are also not detected (e.g. ldap://ldap.example.com:ABC/...)

**Comment by tiran** [comment]
``isLDAPUrl`` is no does not verify or even parse the URL. The function is not intended as validator. It only checks if the beginning or an URL looks like an LDAP url.
