### ISSUE TITLE
"no value-spec" error with latest version

### ISSUE THREAD

**Issue by madhavamk** [python-ldap/python-ldap#352]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.
Getting "no value-spec" error when trying to parse a LDIF file.
---

Issue description:
I have an LDIF file where in "userPrincipalName" field of LDIF is on one line, the value associated with this key is in another line. This is resulting in "no value-spec" error being raised from the ldif.py file, "_next_key_and_value" method. 

Steps to reproduce: 
Have an LDIF file, where any key value is in one line and the corresponding value is in another.

Operating system:
Amazon Linux 

Python version: 
3.6

python-ldap version: 
Latest

**Comment by encukou** [comment]
Can you share a sample of your LDIF file?

**Comment by tiran** [comment]
Does the LDIF file work with ``ldapmodify -f your.ldif``?

**Comment by madhavamk** [comment]
> Can you share a sample of your LDIF file?

Here you go!!


[LDIF_line_test.zip](https://github.com/python-ldap/python-ldap/files/4748450/LDIF_line_test.zip)

**Comment by tiran** [comment]
The LDIF is:
```
dn: CN=Student1,OU=Automation,OU=Funtional,OU=Testing,DC=utkarsh,DC=com
changetype: add
Hash: ...
sAMAccountName: student1
primaryGroupID: 513
userPrincipalName:
student1@utkarsh.com
memberOf: CN=Students,CN=Users,DC=utkarsh,DC=com
memberOf: CN=Bromance Group,CN=Users,DC=utkarsh,DC=com
```

The LDIF file is not valid according to https://linux.die.net/man/5/ldif.

**Comment by madhavamk** [comment]
Thanks for pointing me the LDIF being invalid. I did try by giving a trailing space in the LDIF, that indeed got processed.
