### ISSUE TITLE
enabling start_tls for a schema.urlfetch request

### ISSUE THREAD

**Issue by darkedges** [python-ldap/python-ldap#367]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
I am unable to figure out the options for enabling `start_tls` via a `schema.urlfetch`
The documentation says there is an extension option, but not much details seems to be given about how to find supported extensions or add them to the `uri`
For example the following fails.

```
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
ldapConn = ldap.initialize('ldap://xxxxx:11389')
ldapConn.start_tls_s()
ldapConn.simple_bind_s('xxxx', 'xxxx')
subschemasubentry_dn, schema = ldap.schema.urlfetch('ldap://xxxxx:11389????bindname=xxxx,X-BINDPW=xxxx')
ldapConn.unbind_s()
```

Any ideas on how I can get the schema on a `start_tls` enabled connections?

Steps to reproduce: 
See above

Operating system: 
RHEL 7.3

Python version: 
Python 2.7.5

python-ldap version: 
3.2.0

**Comment by tiran** [comment]
``ldap.schema.urlfetch`` does neither support StartTLS nor reuse of an existing connection. I recommend that you fetch the schema differently:

```
conn = ldap.initialize('ldap://xxxxx:11389')
conn.start_tls_s()
conn.simple_bind_s('xxxx', 'xxxx')

# get DN of the schema entry from DIT
schema_dn = conn.search_subschemasubentry_s()
# retrieve schema
schema_entries = conn.read_subschemasubentry_s(schema_dn)
# parse schema
schema = ldap.schema.SubSchema(schema_entries)
```

**Comment by darkedges** [comment]
Thank @tiran will try that

**Comment by darkedges** [comment]
Thanks @tiran worked a treat.
