### ISSUE TITLE
No results returned when requesting a ldap search

### ISSUE THREAD

**Issue by mlpcorreia** [python-ldap/python-ldap#369]
Issue description:

I'm having problems when executing a ldap search. With ldapsearch I get results, but with python-ldap no results are returned. In debug mode I can't find any problem. The code and the filter:
`
f = '(&(objectClass=person)(oiNSP0Auth=TRUE))'
search = conn.search(base, scope, f, ['cn', 'groupMembership'])
result = conn.result(search, 60)
`

I'm connecting with a ldap server that has ssl, but I'm ignoring it with ` ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)`

Operating system: Red Hat Enterprise Linux Server 7.7

Python version: 3.6.8

python-ldap version: 3.2.0

**Comment by mistotebe** [comment]
You'll need to provide more information before more can be done about this, at least the error returned and preferably logs too.
