### ISSUE TITLE
Pytest fixtures

### ISSUE THREAD

**Issue by azmeuk** [python-ldap/python-ldap#372]
python-ldap version: 3.3.0

There is some [unittest testcases](https://www.python-ldap.org/en/python-ldap-3.3.0/reference/slapdtest.html) provided by python-ldap. It would be awesome if it could also provide some pytest fixtures.

I think there is not a lot of work, I can provide a patch. I just want to check if this patch is wanted, else I can create a `pytest-ldap` module.

What do you think?

**Comment by azmeuk** [comment]
I just created the package `pytest-ldap`, so python-ldap until 3.3.0 can benefit those fixtures.

https://gitlab.com/yaal/pytest-ldap/

**Comment by encukou** [comment]
Hello,
I think test cases for other frameworks like pytest should be in a separate project, where they can be e.g. tested appropriately.
Do you want to send a PR adding a link to https://pypi.org/project/pytest-ldap/ to python-ldap's documentation?

**Comment by azmeuk** [comment]
I'll do that.
