### ISSUE TITLE
Can't install on Debian stretch anymore

### ISSUE THREAD

**Issue by ikus060** [python-ldap/python-ldap#375]
Lately, my pipe line is failing to install python-ldap for Debian stretch. This is obviously something new. Cause everything was working last week.

See https://gitlab.com/ikus-soft/rdiffweb/-/jobs/712206347
---

Issue description:

Steps to reproduce: 

Pip install python-ldap
Failed in Debian stretch

Operating system: 
Debian stretch

Python version: 
Python 3.5

python-ldap version: 
Latest

**Comment by encukou** [comment]
This ooks like an issue in setuptools 50.0, see https://github.com/pypa/setuptools/issues/2357 and https://github.com/pypa/setuptools/issues?q=is%3Aissue+is%3Aopen

**Comment by ikus060** [comment]
@encukou Thanks alot for your quick replies.
What a mess !
Do you plan to do something special in python-ldap like black listing setuptools 50.0.0 ? What would be the recommendation ?

**Comment by encukou** [comment]
I hope setuptools will do a fix soon; I'm afraid there are no plans for a fix in python-ldap.
If you need a workaround *right now*, try setting [`SETUPTOOLS_USE_DISTUTILS=stdlib`](https://setuptools.readthedocs.io/en/latest/history.html#v50-0-0). You might also need to [configure Tox](https://tox.readthedocs.io/en/latest/example/basic.html#passing-down-environment-variables) to see it.

**Comment by ikus060** [comment]
@encukou Thanks alot for the info. Will keep track of it in setuptools project then, Closing this issue.
