### ISSUE TITLE
SlapdObject configuration methods

### ISSUE THREAD

**Issue by azmeuk** [python-ldap/python-ldap#377]
python-ldap version: 3.3.0

SlapdObject creates a server configured by a configuration file, and this method is deprecated in favor of a configuration directory. Also it seems this prevents some actions to be doable with `slapadd`, that I would like to implement (see #373).

What would you think of making SlapdObject spawn a directory configured slapd server? This could be optional or by default.

I volunteer to provide a patch.

**Comment by encukou** [comment]
That could work.
Could you link to the deprecation notice for configuration files? I'm not all that familiar with slapd.

**Comment by azmeuk** [comment]
[This piece of documentation](https://www.openldap.org/doc/admin24/slapdconf2.html) describe how to configure slapd conf directory, and says that:

> The older style slapd.conf(5) file is still supported, but its use is deprecated and support for it will be withdrawn in a future OpenLDAP release. Configuring slapd(8) via slapd.conf(5) is described in the next chapter.
