### ISSUE TITLE
Trouble with IPv6 ldap connection

### ISSUE THREAD

**Issue by PeedusJoy** [python-ldap/python-ldap#379]
Tried binding to a PHP LDAP server using IPv6 address  , but no luck. 
--

Issue description:

I am trying to make a binding to PHP ldap server with IPV6 address. 
Connection works from another application, so the server doesnt seems to have an issue.

Steps to reproduce: 

import ldap

    l = ldap.initialize("ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd]:636")
    l.simple_bind_s("cn=user1,ou=riverpool,dc=cnet,dc=in","P@ssw0rd")

--- I get below error -----------

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 454, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 448, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\compat.py", line 46, in reraise
    raise exc_value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []}

Operating system: 
     Windows Server 2016

Python version: 
     Python 3.8.4

python-ldap version: 
     3.3.1

**Comment by tiran** [comment]
Is your LDAP server bound to TCP6 port and not just to TCP4 port? Are you able to connect to the address and port?

```
>>> import socket
>>> socket.create_connect(("2607:f2b1:f083:139:20c:29ff:fe81:fecd", 636))
```

**Comment by PeedusJoy** [comment]
Thank you for the response.
I think it is bound to TCP6 port as well, because I was able to bind through ipv6 from another application.

Here is the output from socket connection-

>>> socket.create_connection(("2607:f2b1:f083:139:20c:29ff:fe81:fecd", 636))
<socket.socket fd=432, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('2607:f2b1:f083:149::2ed', 53459, 0, 0), raddr=('2607:f2b1:f083:139:20c:29ff:fe81:fecd', 636, 0, 0)>

**Comment by tiran** [comment]
Please increase the global debug level with ``ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)`` and then try to connect. You should get a bunch of debug messages on stderr.

**Comment by PeedusJoy** [comment]
I hardly had luck getting more debug information increasing the debug level . Also enabled the trace_level=2 for initialize method and got a few more lines in the output.
I will try more on this tomorrow..


*** <ldap.ldapobject.SimpleLDAPObject object at 0x0128E700> ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd] - SimpleLDAPObject.set_option
((17, 3), {})
=> result:
None
*** <ldap.ldapobject.SimpleLDAPObject object at 0x0128E700> ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd] - SimpleLDAPObject.simple_bind
(('cn=user1,ou=riverpool,dc=cnet,dc=in',
  'P@ssw0rd',
  None,
  None),
 {})
=> LDAPError - SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []}

**Comment by PeedusJoy** [comment]
As an update to this issue -

I am able to get the [IPV6-address] working on RHEL OS with open ldap package installed.
The issue with windows server 16 still exists.

**Comment by tiran** [comment]
I need to see a connection attempt with maximum debug level of libldap. Trace level is not relevant. libldap should print a additional information to stderr:

```
>>> import ldap
>>> ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)
>>> l = ldap.initialize("ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd]:636")
ldap_create
ldap_url_parse_ext(ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd]:636)
>>> l.simple_bind_s("cn=user1,ou=riverpool,dc=cnet,dc=in","P@ssw0rd")
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP 2607:f2b1:f083:139:20c:29ff:fe81:fecd:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 2607:f2b1:f083:139:20c:29ff:fe81:fecd 636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect: 

```

**Comment by PeedusJoy** [comment]
Thank you again for looking into this.

I have enable same debug level but not able to see any different messages:
Please see the complete console output copied:

---------------------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Trshoot>python
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:30:28) [MSC v.1926 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)
>>> l = ldap.initialize("ldaps://[2607:f2b1:f083:139:20c:29ff:fe81:fecd]:636")
>>> l.simple_bind_s("cn=user1,ou=riverpool,dc=cnet,dc=in","P@ssw0rd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 454, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 448, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\compat.py", line 46, in reraise
    raise exc_value
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ldap\ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': []}
>>>

**Comment by tiran** [comment]
I'm starting to suspect that your build of OpenLDAP and python-ldap binaries does neither support debug logging nor IPv6. How did you build the package and its dependencies?

**Comment by PeedusJoy** [comment]
I had installed the .whl file

Had done a pip install of python-ldap package available here :

https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-ldap

pip install python_ldap-3.3.1-cp38-cp38-win_amd64.whl

**Comment by PeedusJoy** [comment]
Also, On windows I did not have any explicit install of OpenLDAP. I was assuming that since IPV4 works, it uses the available OpenLDAP version.

**Comment by tiran** [comment]
python-ldap is a wrapper for OpenLDAP's libldap client library. It's possible that Gohlke's build of OpenLDAP does not support IPv6 and debug logging correctly. I suggest that you contact him and ask for more information. I don't have access to Windows build system or his build infrastructure.

**Comment by PeedusJoy** [comment]
I think that is where the issue is..  On RHEL I could do a pip install python-ldap successfully.
Thanks for helping to understand the problem. 
Will try to get the windows installation with right version of OpenLDAP.
