### ISSUE TITLE
"DEPRECATION: Could not build wheels for python-ldap which do not use PEP 517"

### ISSUE THREAD

**Issue by polarathene** [python-ldap/python-ldap#380]
**Issue description:**

Not a python developer so I may have made a mistake here. Attempting to build a python project that uses this package, but fails. 

From what I've seen on this repo's issues, "wheels" aren't something the project intends to support, so that deprecation warning may not matter. I also recall seeing mention of needing a system dependency installed, so I'll look into that, just sharing the following output to this project as nothing came up about the PEP 517 deprecation when searching issues here.

```
ERROR: Failed building wheel for python-ldap                                                                                                                                                                                    
  Running setup.py clean for python-ldap
Failed to build python-ldap
DEPRECATION: Could not build wheels for python-ldap which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.                                                                                                             
Installing collected packages: pyasn1, pyasn1-modules, python-ldap
    Running setup.py install for python-ldap: started
    Running setup.py install for python-ldap: finished with status 'error'
```

Further down in the log is:

```
    building '_ldap' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/Modules
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.3.1 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULCENSE=Python style -IModules -I/usr/local/include/python3.8 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.8/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:3:
    Modules/common.h:15:10: fatal error: lber.h: No such file or directory
     #include <lber.h>
              ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Steps to reproduce:** 

```Dockerfile
FROM python:3.8-buster

WORKDIR /src
RUN git clone "https://github.com/plinss/bindtool.git" --single-branch \
  && cd /src/bindtool \
  && pip install --no-cache-dir -r requirements.txt
```

**Operating system:** Docker (Debian Linux - Buster) / Host (Manjaro Linux)

**Python version:** 3.8

**python-ldap version:** `python-ldap>=3.2.0` (from `requirements.txt`)

**Comment by polarathene** [comment]
I added the dependencies `libldap2-dev libsasl2-dev` mentioned in the docs for debian. `build-essential python3-dev python2.7-dev` were all skipped as build tools and python3 are part of the image. 

I did not need `slapd ldap-utils python-tox lcov valgrind` dependencies to have a successful (error free) build. I assume they're required for some ldap functionality if accessed at runtime? Personally I'm not using LDAP with the referenced project, it just doesn't make it clear if that can be opt-out to drop the dependency.

**Comment by encukou** [comment]
As said in the pip issue, the `DEPRECATION` warning is misleading; the error is missing LDAP libraries and pip won't solve that by falling back to legacy `setup.py install`.

The `slapd ldap-utils python-tox lcov valgrind` packages are needed for tests, you can indeed build without them – tough over here, best practice is to run the test suite after a build.
Does it work with `libldap2-dev libsasl2-dev` installed?

**Comment by polarathene** [comment]
> Does it work with `libldap2-dev libsasl2-dev` installed?

Yes, although I don't use any LDAP functionality to confirm that actually works, but the project installed successfully and I was able to use it for what I wanted.
