### ISSUE TITLE
cidict no longer defines a .copy() method

### ISSUE THREAD

**Issue by mistotebe** [python-ldap/python-ldap#387]
Issue description:

At some point, cidict.copy() disappeared.

Steps to reproduce: 

```python3
from ldap.cidict import cidict
d = cidict()
d.copy()
```

Used to work, now `.copy()` is no longer a method.

Operating system: Linux
Python version: 3.8
python-ldap version: 3.3.1

**Comment by encukou** [comment]
The `cidict` API was never really documented, but I think that for backwards compatibility reasons, `copy` should be part of it.

AFAIK that's the only API `dict` had in Python 2 but `MutableMapping` doesn't have. (We don't need to implement `__or__` or `__reversed__`, which `dict` got relatively recently.)

**Comment by tiran** [comment]
``collections.UserDict`` implements a bunch of extra methods on top of MutableMapping. copy() is not provied by MutableMapping.

**Comment by mistotebe** [comment]
Do you have a timeline when this might get released?
