### ISSUE TITLE
PostReadControl decodes values in ISO8859-1

### ISSUE THREAD

**Issue by spaceone** [python-ldap/python-ldap#399]
The PostReadControl decodes the attribute values in ISO8859-1.
```python
from ldap.controls.readentry import PostReadControl
[PostReadControl(True, ['entryUUID', 'entryCSN', 'displayName'])]
```
using this control result in:
```
>>> ctrls
<ldap.controls.readentry.PostReadControl object at 0x7f10d1e738d0>
>>> ctrls.entry
{'entryUUID': ['5d96cc2c-8e13-103a-8ca5-2f74868e0e44'], 'displayName': ['Ã\x84dministrator3'], 'entryCSN': ['20201122182218.677180Z#000000#000#000000']}
>>> print(ctrls.entry['displayName'][0].encode('latin-1').decode('UTF-8'))
Ädministrator3
```
I would have expected the attributes to be `bytes`, not `str(/unicode)`. Or at least take the correct encoding from the LDAP server schema.

**Comment by spaceone** [comment]
So from my perspective a correct fix would be:
```diff
diff --git Lib/ldap/controls/readentry.py Lib/ldap/controls/readentry.py
index c5db424..7b2a7e8 100644
--- Lib/ldap/controls/readentry.py
+++ Lib/ldap/controls/readentry.py
@@ -42,7 +42,7 @@ class ReadEntryControl(LDAPControl):
     self.dn = str(decodedEntry[0])
     self.entry = {}
     for attr in decodedEntry[1]:
-      self.entry[str(attr[0])] = [ str(attr_value) for attr_value in attr[1] ]
+      self.entry[str(attr[0])] = [ bytes(attr_value) for attr_value in attr[1] ]
 
 
 class PreReadControl(ReadEntryControl):

```

This is of course an API change. Don't know under what circumstances you can do this.

`attr_value` in this case is a
`<AttributeValue value object at 0x7efe18dbe518 tagSet <TagSet object at 0x7efe1b0569e8 tags 0:0:4> encoding iso-8859-1 payload [0xc384646d696e6973747261746f7234]>`, which contains a `__bytes__()` method.

**Comment by encukou** [comment]
> This is of course an API change. Don't know under what circumstances you can do this.

In a new major version. Since the current master branch will become 4.0, this can go in. Can you send a PR?

**Comment by spaceone** [comment]
> > This is of course an API change. Don't know under what circumstances you can do this.
> 
> In a new major version. Since the current master branch will become 4.0, this can go in. Can you send a PR?
Yes, here you go: https://github.com/python-ldap/python-ldap/pull/400
