### ISSUE TITLE
Ignoring false positive error checks when raising ldap.LDAPError in tests

### ISSUE THREAD

**Issue by romainr** [python-ldap/python-ldap#404]
Hello,

I spent quite some time digging on this but could not find a proper way to do it and looking for ideas.

We have a suite of tests handling LDAP errors. Those raise a [ldap.LDAPError](https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html) exception: 

```
  def test_ldap_exception_handling(self):
    # Set up LDAP tests to use a LdapTestConnection instead of an actual LDAP connection
    class LdapTestConnectionError(LdapTestConnection):
      def find_users(self, user, find_by_dn=False):
        raise ldap.LDAPError('No such object')
```

https://github.com/cloudera/hue/blob/707a833cbea46818576f4273c60eb0e4b113010f/apps/useradmin/src/useradmin/test_ldap.py#L797

However, this triggers a Github "Unchanged files with check annotations" in the PRs:
https://github.blog/changelog/2019-09-06-improved-check-annotations-on-the-files-changed-tab/

![image](https://user-images.githubusercontent.com/56080867/111504492-f2ea6a80-8704-11eb-8ebe-12887ec28902.png)

e.g. Bottom of "Unchanged files with check annotations"
https://github.com/cloudera/hue/pull/1906/files

Not sure if related to Python warnings
https://github.com/cloudera/hue/blob/master/.github/workflows/commitflow-py3.yml#L47

I have been trying to silence the warning via https://github.com/cloudera/hue/pull/1905/files with no change.

Would someone have some recommendations about how to disregard those warnings? Thanks!

**Comment by mistotebe** [comment]
I'm pretty sure this has nothing to do with this python-ldap module except for the fact you're reusing our Exception type.
