### ISSUE TITLE
pyasn1.error.PyAsn1Error: Attempted "__iter__" operation on ASN.1 schema object

### ISSUE THREAD

**Issue by chvakhil** [python-ldap/python-ldap#406]
Issue description: Getting `pyasn1.error.PyAsn1Error: Attempted "__iter__" operation on ASN.1 schema object` 

Code:
```
import ldap
def authenticate(address, username, password):
    conn = ldap.initialize('ldap://' + address)
    conn.protocol_version = 3
    conn.set_option(ldap.OPT_REFERRALS, 0)
    return conn.simple_bind_s(username, password)
print(authenticate(address='localhost:10386', username='jdoe', password='admin'))
```

Steps to reproduce: 
1. Create .py file with above code and run 

Operating system:  Windows 10 Pro

Python version:  3.6.2

python-ldap version:  python3-ldap-0.9.8.4

**Comment by tiran** [comment]
python3-ldap is a different project and not related to python-ldap at all. The project was renamed to ``ldap3`` in 2015:

https://pypi.org/project/python3-ldap/

> python3-ldap HAS BEEN RENAMED ldap3 to avoid confusion with the former python-ldap project.
