### ISSUE TITLE
Single failing test on python3.9 when run with pytest 6.2

### ISSUE THREAD

**Issue by rmcgibbo** [python-ldap/python-ldap#407]
Hello,

I noticed that the Nixpkgs builds for python-ldap recently started failing for python3.9. I believe the relevant update on the nixpkgs side that triggered the failure to appear was going from pytest 6.1.2 to pytest 6.2.2

1. Here's a link showing the build status over time
    *  https://hydra.nixos.org/job/nixpkgs/trunk/python39Packages.ldap.x86_64-linux
2. Here's the failing test log. It's just `Test03_SimpleLDAPObjectWithFileno.test_simple_bind_noarg`
    *  https://nix-cache.s3.amazonaws.com/log/zgrkc8wpfrm4pba2lvymhs386gffn8sq-python3.9-python-ldap-3.3.1.drv

I noticed that when I run the python3.9 tests using the same cmdline that [you use in tox.ini](https://github.com/python-ldap/python-ldap/blob/master/tox.ini#L16-L17), the same tests pass. 

/xref https://github.com/NixOS/nixpkgs/pull/117614
cc https://github.com/python-ldap/python-ldap/issues/396

I don't know exactly what's going on, and it's not a particularly big deal (nixpkgs can run the tests using python -m unittest discover), but I thought it worth bringing to your attention.

Operating system: `x86_64-linux`
Python version: `cpython-3.9`
python-ldap version: `3.3.1`

**Comment by mistotebe** [comment]
Hi @rmcgibbo, I can see the tests didn't fail at all since on that link, how did you resolve this? Also did you find a way to reproduce this locally?

**Comment by rmcgibbo** [comment]
Sorry, I actually don't know. This is pretty much paged out for me, it looks I just noticed it when nixos was prepping for a release last year. If it's fixed now, it probably means that someone has since pushed a fix of some sort to nixpkgs and it's all good now.
