### ISSUE TITLE
Getting `AttributeError: module 'base64' has no attribute 'decodestring'` error while running on python 3.9.6

### ISSUE THREAD

**Issue by rasrivas-redhat** [python-ldap/python-ldap#426]
Issue description:

Getting `AttributeError: module 'base64' has no attribute 'decodestring'` error while running on python 3.9.6

Steps to reproduce: 

Below is a dummy program, while running on python 3.9.6, I am getting `AttributeError: module 'base64' has no attribute 'decodestring'`` error:

```
from ldif3 import LDIFParser

parser = LDIFParser(open('dse3.ldif', 'rb'))
for dn, entry in parser.parse():
    if dn == "cn=Schema Compatibility,cn=plugins,cn=config":
        if entry['nsslapd-pluginEnabled'] == ['on']:
            print('Entry record: %s' % dn)
```

Error message:

```
python3.9 1.py                              ✔    venvpy3.9   11:12:01 
Traceback (most recent call last):
  File "/Users/rasrivas/local_test/1.py", line 4, in <module>
    for dn, entry in parser.parse():
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 384, in parse
    yield self._parse_entry_record(block)
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 357, in _parse_entry_record
    attr_type, attr_value = self._parse_attr(line)
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 315, in _parse_attr
    attr_value = base64.decodestring(line[colon_pos + 2:])
AttributeError: module 'base64' has no attribute 'decodestring'
```

python version

```
python --version 
Python 3.9.6
```

Operating system: 

macOS 11.5.2

Python version: 

```
python --version 
Python 3.9.6
```

python-ldap version: 

`ldif3-3.2.2`

**Comment by rasrivas-redhat** [comment]
As I was getting below error:

```
Traceback (most recent call last):
  File "/Users/rasrivas/local_test/1.py", line 4, in <module>
    for dn, entry in parser.parse():
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 384, in parse
    yield self._parse_entry_record(block)
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 357, in _parse_entry_record
    attr_type, attr_value = self._parse_attr(line)
  File "/Users/rasrivas/local_test/venvpy3.9/lib/python3.9/site-packages/ldif3.py", line 315, in _parse_attr
    attr_value = base64.decodestring(line[colon_pos + 2:])
AttributeError: module 'base64' has no attribute 'decodestring'
```

I updated the code from `attr_value = base64.decodestring(line[colon_pos + 2:])` to `attr_value = base64.decodebytes(line[colon_pos + 2:])` for the file `/ldif3.py` (/{..}/venvpy3.9/lib/python3.9/site-packages/ldif3.py) and it worked for me.

From the doc: https://docs.python.org/3.8/library/base64.html#base64.decodestring, base64.decodestring(s) is depricated since version 3.1.

Can we please update the code to make it compatible with all the python 2 and 3 versions?

**Comment by tiran** [comment]
``ldif3`` is a deprecated [fork](https://github.com/xi/ldif3) of python-ldap and not maintained by us. Please use the ``ldif`` module from python-ldap.

**Comment by rasrivas-redhat** [comment]
Thanks for the information.

**Comment by rasrivas-redhat** [comment]
@tiran - I have another question related to it would be great if you answer it. As per the doc: https://ldif.readthedocs.io/en/latest/, it says `This package only supports Python 3 (>= 3.7, actually)`, if we have a requirement to support py2.6 and 2.7 as well.

I made a test with py 2.7 to just check the support, but it throws an error:

```
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from ldif import LDIFParser
  File "/Users/rasrivas/local_test/venvpy27/lib/python2.7/site-packages/ldif.py", line 242
    encoding: Optional[str] = "utf8",
            ^
SyntaxError: invalid syntax
``` 

 Is there any alternative or workaround to support py2.6 and 2.7 as well?

**Comment by tiran** [comment]
That's not the ``ldif`` from python-ldap. You must have installed yet another package that ships an ``ldif`` module.

**Comment by rasrivas-redhat** [comment]
Yes, I was using another package, `ldif` from python-ldap is working fine. Thanks.

**Comment by rasrivas-redhat** [comment]
Hello @tiran, I have one more question, while testing more `python-ldap` libraries on different python releases, I found it works well with py 2.7, 3.6, 3.7, and 3.9 but I was facing an issue with py 2.6, then I went through the document (https://www.python-ldap.org/en/python-ldap-3.3.0/installing.html#build-prerequisites) it also says, Python version 2.7, or 3.4 or later is supported.

I have a requirement to support py 2.6, is there is a workaround?

**Comment by tiran** [comment]
We only support Python >= 3.6. Anything older is out of scope.

You may find an older release on PyPI that works with ancient versions of Pythons. Please be advised that old versions may contain known bugs and known security issues.

**Comment by rasrivas-redhat** [comment]
Thanks for the information.
