### ISSUE TITLE
Release upcoming? 

### ISSUE THREAD

**Issue by Firstyear** [python-ldap/python-ldap#434]
There are some changes that appear to have resolved issues with openldap 2.5, and some other things changed that would be nice to have. Is there a plan for a release soon? Is it worth having a fixed release schedule just to encourage this process to occur more frequently?

**Comment by quanah** [comment]
As I noted in issue#432, it is not currently compatible with stock OpenLDAP 2.5, as far as building/linking to the LDAP libraries is concerned.

**Comment by Firstyear** [comment]
Yes, it would be good to have 2.5 compat in an upcoming release then, so it's still good to have this open.

**Comment by mistotebe** [comment]
Yes, 3.4.1 which will build against OpenLDAP 2.5 without having to tweak setup.cfg is coming soon: https://github.com/python-ldap/python-ldap/milestone/6

**Comment by georgkrause** [comment]
@mistotebe Hi and thank you for all the great work here! I really appreciate you did everything to make python-ldap compatible with openldap 2.5. It seems like everything is in place for the release already, or am I wrong? Is there anything to do to help get it shipped?
