### ISSUE TITLE
Can't use ReconnectLDAPObject to bind because of TypeError

### ISSUE THREAD

**Issue by jnewbigin** [python-ldap/python-ldap#448]
Issue description:
Using `ReconnectLDAPObject` results in an error:
`TypeError: _store_last_bind() got multiple values for argument 'method'`

Steps to reproduce: 

```
connection = ldap.ldapobject.ReconnectLDAPObject(uri=uri, bytes_mode=False)
connection.bind_s(bind_dn, password, method=ldap.AUTH_SIMPLE)
```

`bind_s` invokes `self._store_last_bind`

```
self._store_last_bind(method=SimpleLDAPObject.bind_s,*('username', 'password'),**{'method': 128})
```
Which has 2 parameters called method and hence the exception.

In my case, I can omit the `method=ldap.AUTH_SIMPLE` but if I needed a different auth method then it would not work.

Operating system: 
Linux

Python version: 
3.8.11

python-ldap version: 
python-ldap==3.3.1

**Comment by mistotebe** [comment]
I guess it's a good thing LDAP never really used a different AuthenticationChoice than `simple` and `sasl`, so noone has a reason to use the method parameter.

In any case, the first argument to `_store_last_bind` should be renamed to something else since that's an internal API and something we can fix without breaking users.

**Comment by jnewbigin** [comment]
I think we were just being extra careful with our original code and specifying everything even though the defaults were OK.

**Comment by mistotebe** [comment]
> I think we were just being extra careful with our original code and specifying everything even though the defaults were OK.

Hi @jnewbigin, could you confirm #471 works as expected?
Thanks

**Comment by jnewbigin** [comment]
:+1: works great thanks.
