### ISSUE TITLE
modify_s always update attributes wilth null value 

### ISSUE THREAD

**Issue by normansu-tw** [python-ldap/python-ldap#450]
Issue description:

Here is my code:

```
#!/bin/env python3
import os, sys
import ldap
import time

url = "ldaps://ldaphost.test.com:636" 
dn = 'CN=test1,OU=XXX,OU=XXX,DC=ldaphost,DC=test,DC=com'
user = 'user'
password = '....'
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
ldap_conn = ldap.initialize(url, trace_level=0)

sasl_auth = ldap.sasl.sasl(
    {
        ldap.sasl.CB_AUTHNAME: user,
        ldap.sasl.CB_PASS: password
    },
    'DIGEST-MD5' 
)   
ldap_conn.protocol_version = 3
ldap_conn.set_option(ldap.OPT_REFERRALS, 0)
ldap_conn.set_option(ldap.OPT_X_TLS,ldap.OPT_X_TLS_DEMAND)
ldap_conn.set_option(ldap.OPT_X_TLS_DEMAND, True )
ldap_conn.set_option(ldap.OPT_DEBUG_LEVEL, 255 )
ldap_conn.sasl_interactive_bind_s("", sasl_auth)

ldif = [(ldap.MOD_REPLACE, 'comment', ["balabala".encode('utf-16be')])]
res = ldap_conn.modify_s(dn, ldif)
ldap_conn.unbind_s()
```

Steps to reproduce: 

1. Execute with the code above.
2. Before Update
![圖片](https://user-images.githubusercontent.com/10781048/146340091-c0473da1-4c27-4bfb-af0a-9d47e8b8b5af.png)

3. After update
![圖片](https://user-images.githubusercontent.com/10781048/146340194-0f2d4d9b-7dfc-48ba-b2c3-7f2b76e8a943.png)

4. change the ldif with DELETE old_value and ADD new_value, I still get the same result.

Operating system: 
Ubuntu 20.04.3 LTS
Windows Server 2012 

Python version: 
3.8.10

python-ldap version: 
3.4.0

**Comment by normansu-tw** [comment]
I use ldap3 to verify the result.
I found 
`'comment': '\x00b\x00a\x00l\x00a\x00b\x00a\x00l\x00a',`

there's \x00 inserted before each character.

**Comment by tiran** [comment]
LDAP uses UTF-8, not UTF-16. Please try again with

```
ldif = [(ldap.MOD_REPLACE, 'comment', ["balabala".encode('utf-8')])]
```

**Comment by normansu-tw** [comment]
Thanks for remind me encode
