### ISSUE TITLE
module 'ldap' has no attribute 'filter'

### ISSUE THREAD

**Issue by tippexs** [python-ldap/python-ldap#469]
Issue description:
After installing `python-ldap` using `pip` on Python3.9 I do not have `filter` in `ldap` module.

Update: Explicitly loading / importing `filter` works.
`from ldap.filter import *`

``` python3
ldap.filter
<module 'ldap.filter' from '/home/ubuntu/workspace/nginx/ldap-0day/nginx-ldap-auth/.env/lib/python3.9/site-packages/ldap/filter.py'>
```

Updating the `__init__.py` with
```python
from ldap.filter import *
```
made the filter available after loading `python-ldap` using `import ldap` only.

Steps to reproduce: 
Install `python-ldap` using `pip` by issuing `python3 -m pip install python-ldap`.
Load interactive Python Session `python3`
Import Ldap: `import ldap`
Check Filter `ldap.filter`.
Error:
```python
>>> ldap.filter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap' has no attribute 'filter'
```

Operating system: 
```shell
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish

```
Python version: 
```shell
$ python --version
Python 3.9.7
```
python-ldap version: 
```shell
cat .env/lib/python3.9/site-packages/ldap/pkginfo.py 
"""
meta attributes for packaging which does not import any dependencies
"""
__version__ = '3.4.0'
__author__ = 'python-ldap project'
__license__ = 'Python style'

```

Happy to submit a PR if neede. But as in our projects an Issue always comes first this is it.

**Comment by mistotebe** [comment]
This is intentional and AFAIK documented as such, you want to do this:
`import ldap.filter` or `from ldap.filter import <names>`
