### ISSUE TITLE
can you decouple  python-pyasn1

### ISSUE THREAD

**Issue by alittlesir** [python-ldap/python-ldap#472]
hello,man. i am a develop of using your python-ldap, i find one thing, the python-pyasn1 was not update for a long time. it update two years before, and it is not lively,  i send email to author, and he not reply me. so can you decouple  python-pyasn1

**Comment by mistotebe** [comment]
What is the issue with python-pyasn1 that makes python-ldap unusable for you? I'm not aware of any issues of that sort and the fact the package hasn't seen any updates isn't a cause for concern on its own.

**Comment by alittlesir** [comment]
I am using python-ldap and I find out python-pyasn1 is not active and no one is maintaing python-pyasnl community. If it is possible to delete python-pyasn in python-ldap？

**Comment by mistotebe** [comment]
It is providing a valuable service encoding/decoding control values for us so we can't get rid of it easily. Again, I see no issue using it unless and until there are major issues raised with the library with nobody volunteering to fix them. Are you aware of any?

**Comment by droideck** [comment]
There are no valid reasons to remove pyasn1, as far as we know. The person who opened the issue is silent for a while. Closing.
Please, reopen it if feel it's needed.
