### ISSUE TITLE
issue in python3-ldap when running add_s

### ISSUE THREAD

**Issue by shaheena86** [python-ldap/python-ldap#485]
Hello,

Debian : 11.
Openldap : 2.4.57+dfsg-3+deb11u1
python3-ldap : 3.2.0-4+b3
python3-ldap3: 2.8.1-1
TLS - 1.3
Openssl - 1.1.1n-0+deb11u3

I am try to set a new connect and then import files using below commands:

ldapcon = ldap.initialize('ldap://localhost')
ldapcon.set_option(ldap.OPT_PROTOCOL_VERSION, ldap.VERSION3)
ldapcon.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
ldapcon.set_option(ldap.OPT_X_TLS_NEWCTX, 0)

dn_to_add = 'cn=test.user,ou=people,dc=framework,dc=protegrity,dc=com'

modlist_to_add = [('uid', [b'test.user']), ('objectclass', [b'inetOrgPerson', b'posixAccount', b'top']), ('uidnumber', [b'1003']), ('gidnumber', [b'100']), ('homedirectory', [b'/home/test.user']), ('userpassword', [b'qwer1234']), ('givenname', [b'test']), ('sn', [b'user']), ('displayname', [b'test user']), ('loginshell', [b'/usr/local/sbin/manager']), ('cn', [b'test.user']), ('description', [b'testing']), ('pwdreset', [b'TRUE'])]

*********
But when I run this - ldapcon.add_s(dn_to_add, modlist_to_add)
The slapd service crashes and I get below error

 LDAP Failure: {'desc': "Can't contact LDAP server}
ldap.CONFIDENTIALITY_REQUIRED: {'desc': 'Confidentiality required', 'info': 'TLS confidentiality required'}

Can u guys help me here as in what am I missing on and why the ldap is crashing... it seems to be an issue with python3-ldap as I am able to run the below commands without any issues:

 /usr/bin/ldapsearch -x -s base -ZZ -H `conf-get-value -k LDAP_URI` -D `conf-get-value -k LDAP_BINDDN` -w `conf-get-value -k LDAP_BINDPW` -b `conf-get-value -k LDAP_BASEDN`

Also, When I was using buster and the relavant packages to to buster and python3.7 the same code worked absolutely fine.

Can you guys check and help me here ?

Regards,

Shaheena K

**Comment by tiran** [comment]
The server wants a secure TLS connection even for localhost. You are neither connection on `ldaps://` or do you call `start_tls_s()` to perform STARTTLS.

**Comment by shaheena86** [comment]
Yes, I am using start_tls_s().

snippet:
if ldap_starttls:
       ldapcon.start_tls_s()
ldapcon.simple_bind_s(binddn, bindpw)

**Comment by shaheena86** [comment]
This might give a better picture:
I have taken the LDAP Status after every Line.

>>> import ldap
>>>
>>> bindp_dn = "cn=admin,ou=people,dc=frameworkrepo,dc=shaheena,dc=com"
>>> bindpw = "admin123"
>>>
>>>
>>>
>>> ldapcon = ldap.initialize('ldap://127.0.0.1:389/')
LDAP status: Running (pid=48072)
0 _ldap_call

>>> ldapcon.set_option(ldap.OPT_PROTOCOL_VERSION, ldap.VERSION3)
LDAP status: Running (pid=48072)
0 _ldap_call

>>> ldapcon.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
LDAP status: Running (pid=48072)
0 _ldap_call

>>> ldapcon.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
LDAP status: Running (pid=48072)
0 _ldap_call

>>> ldapcon.start_tls_s()
LDAP status: Running (pid=48072)
0 _ldap_call

>>> ldapcon.simple_bind_s(bindp_dn, bindpw)
LDAP status: Running (pid=48072)
0 _ldap_call

LDAP status: Running (pid=48072)
0 _ldap_call
(97, [], 2, [])

>>> dn_to_add = 'cn=test.user,ou=people,dc=frameworkrepo,dc=shaheena,dc=com'

>>> modlist_to_add = [('uid', [b'test.user']), ('objectclass', [b'inetOrgPerson', b'posixAccount', b'top']), ('uidnumber', [b'1003']), ('gidnumber', [b'100']), ('homedirectory', [b'/home/test.user']), ('userpassword', [b'qwer1234']), ('givenname', [b'test']), ('sn', [b'user']), ('displayname', [b'test user']), ('loginshell', [b'/usr/local/sbin/manager']), ('cn', [b'test.user']), ('description', [b'testing']), ('pwdreset', [b'TRUE'])]
>>>
>>>
>>>
>>>
>>> ldapcon.add_s(dn_to_add,modlist_to_add)
LDAP status: Running (pid=48072)
0
LDAP status: Running (pid=48072)
0 _ldap_call
LDAP Status: Not running (CONFLICT:pid not found)
256 _ldap_call
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 440, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 426, in add_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 758, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 774, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 337, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 321, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server"}

**Comment by quanah** [comment]
If slapd is crashing, that's not a python-ldap issue.  As I already told you, the OpenLDAP 2.4 series is historic and unmaintained. I  would suggest you contact the Debian maintainers for the OpenLDAP package.  Better would be to upgrade to a currently supported OpenLDAP release series and see if you can reproduce the issue.
