### ISSUE TITLE
LDAPObject.search attrlist case sensitivity

### ISSUE THREAD

**Issue by BShadeWork** [python-ldap/python-ldap#492]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
Using LDAPObject.search_s(base, scope[, filterstr='(objectClass=*)'[, attrlist=None[, attrsonly=0]]]) → list|None
and assumed the attrlist as case insensitive, but these seems not to be the case.
As (I believe) most ldap are by default case insensitive on attribute names,  would it be possible to have as flag like case_ignore_attr_types like there is already for  ldap.modlist.modifyModlist where  "If case_ignore_attr_types is a list of attribute type names for which the comparison will be conducted case-insensitive."

Or maybe I have it wrong!

Steps to reproduce: 
Use search_s with a attrlist but the ldap attributes have a  different case to the list

Operating system: 
RHEL 6.8
Python version: 
Python 3.6.8

python-ldap version: 
3.3.1

**Comment by quanah** [comment]
Attribute names are case insensitive per RFC.  An LDAP server that enforces case sensitivity on the names of attributes is in violation of the RFC. What LDAP server did you encounter that makes use of case sensitive attribute names?

**Comment by BShadeWork** [comment]
Confused! The ldap server is doing case insensitive and is not enforcing case sensitivity, and returns mixed lower and upper case, but when I put in a list of attributes (in lower) in search_s, if does not grab the values when the attribute name case is different to the attributes listed only when it matches the case exactly. I tried various ways at could not get it to work and it only returned case matching attributes (even though there are case mismatched attributes available on the ldap server)

**Comment by BShadeWork** [comment]
OK apologies. Got a colleague to triple check and it works for them so must have done something wrong in my code. Sorry!
