### ISSUE TITLE
Documentation i.e. examples on ldif.ParseLDIF seem to be wrong

### ISSUE THREAD

**Issue by entomologe** [python-ldap/python-ldap#502]
Issue description:

I was recently using the module ldif from python-ldap (3.2.0-4) included in the Debian Repository which worked just fine, but when I upgraded to ldif-4.1.3 via pip3 parsing doesn't work anymore as described in the documentation: https://www.e.org/en/latest/reference/ldif.html

When using the very bottom example (see also below) the following simple ldif file gets parsed fine with the former ldif but not with the latter.

Steps to reproduce: 

```
$ cat <<EOF > test.ldif
dn: cn=Barbara Fritchy,ou=Sales,o=Oracle,c=US;
work-phone: 650/506-7000;
home-phone: 415/697-8899
EOF

$ cat <<EOF > test.py
#!/usr/bin/env python3
import sys
from ldif import LDIFParser,LDIFWriter

SKIP_DN = ["uid=foo,ou=People,dc=example,dc=com",
   "uid=bar,ou=People,dc=example,dc=com"]

class MyLDIF(LDIFParser):
   def __init__(self,input,output):
      LDIFParser.__init__(self,input)
      self.writer = LDIFWriter(output)

   def handle(self,dn,entry):
      if dn in SKIP_DN:
        return
      self.writer.unparse(dn,entry)

parser = MyLDIF(open("test.ldif", 'rb'), sys.stdout)
parser.parse()
EOF

$ sudo apt install python3-ldap
$ ./test.py
dn: cn=Barbara Fritchy,ou=Sales,o=Oracle,c=US;
home-phone: 415/697-8899
work-phone: 650/506-7000;
$ pip3 install ldif
$ ./test.py
$


```
Operating system: Debian GNU/Linux 11

Python version: 3.9.2

python-ldap version: 3.2.0-4

**Comment by mistotebe** [comment]
Installing the `ldif` package from pip will actually get you [this project](https://github.com/abilian/ldif) rather than python-ldap. It's quite likely that their API is subtly different than ours.
