### ISSUE TITLE
Filter with 'AND' (&) condition not found

### ISSUE THREAD

**Issue by terentev-mn** [python-ldap/python-ldap#504]
Issue description:
I try search all groups of user and use filter, but it return nothing
`  (&(memberUid=m.terentev)(objectClass=posixGroup))`

if search members of group all fine - returnes list of users
`  (cn=some_group)`

for test  I search with 'OR' condition it works.
`  (|(memberUid=m.terentev)(objectClass=posixGroup))`

Steps to reproduce: 
```
In [1]: import ldap
   ...: lc = ldap.initialize("ldap://ipa.ex.net")
   ...: lc.simple_bind_s("uid=srv_user,cn=sysaccounts,cn=etc,dc=ex,dc=net", "xxxxxxxxx")
   ...: len(lc.search_s('dc=ex,dc=net', ldap.SCOPE_SUBTREE, '(&(memberUid=m.terentev)(objectClass=posixGroup))'))
Out[1]: 0

In [2]: len(lc.search_s('dc=ex,dc=net', ldap.SCOPE_SUBTREE, '(|(memberUid=m.terentev)(objectClass=posixGroup))'))
Out[2]: 528

In [3]: len(lc.search_s('dc=ex,dc=net', ldap.SCOPE_SUBTREE, '(objectClass=posixGroup)'))
Out[3]: 528

In [4]: len(lc.search_s('dc=ex,dc=net', ldap.SCOPE_SUBTREE, '(cn=some_group)'))
Out[4]: 1
```

Operating system: 
Ubuntu 22.04
Python version: 
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
python-ldap version:
I tried both versions separatly 
3.2.0-4ubuntu7.1
3.4.3 (from pip)

**Comment by terentev-mn** [comment]
Resolved, my freeipa server creates groups with objectClass posixgroup and not posixGroup

**Comment by quanah** [comment]
objectClass values should be treated as case insensitive.  If freeipa is forcing case sensitivity on that attribute then you should file a bug with them.
