### ISSUE TITLE
Conscious Language: Rename master branch to main branch

### ISSUE THREAD

**Issue by droideck** [python-ldap/python-ldap#509]
As part of the conscious language effort, the master branch is to be renamed to the main branch.

Here are the instructions.

1. Rename the master branch to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
2. Check this to ensure the default branch has been changed to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch - this should keep the github history, as well as updating the default branch configuration and updating any existing PRs

**Comment by encukou** [comment]
Also look through the code, docs/comments tend to mention branch names.
