### ISSUE TITLE
LDAPError not caught by RuntimeError

### ISSUE THREAD

**Issue by Laikulo** [python-ldap/python-ldap#514]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
ldap.LDAPError should be based on PyExc_RuntimeError, and not on PyExc_Exception, because it represents errors that occur at runtime.

Steps to reproduce: 
```python
import ldap
import logging

try:
   ldap.initalize(SOME_URI,..)
   ldap.search_s(some_invalid)
except RuntimeError as err:
  logging.error("Something bad happened",err)
  do_fallback_behavior()
```
  
Workaround: `except (RuntimeError, ldap.LDAPError) as err:`

Operating system: Cent 8 Stream, also observed on OSX 12.6.3

Python version: Observed on 3.6.8 and 3.9.6

python-ldap version: 3.4.3 and 3.3.1

See: https://github.com/python-ldap/python-ldap/blob/b8ad0c5ea7d2c4b295ea636c03124c9e5efb5eea/Modules/constants.c#L212

**Comment by droideck** [comment]
As Python design goes, all user-defined exceptions should be derived from `Exception` class: https://docs.python.org/3/library/exceptions.html?highlight=runtimeerror#Exception

Unless I miss something, there's nothing to fix on the python-ldap side.
