### ISSUE TITLE
ntlm fails on version 3.10.13

### ISSUE THREAD

**Issue by maimorag** [python-ldap/python-ldap#536]
Please describe the issue and your environment here.

---

Issue description:
After updating to python-ldap:3.10.13([docker image details](https://hub.docker.com/layers/demisto/ldap/2.9.1.72637/images/sha256-9bad9d8b3ecc12fd9256062808d0446e3d049ec36a38fdd71a84f94e9edd5020?context=explore)), IO encountered the following bug:
`Failure message: Failed to access LDAP server.`

But when I used version 3.10.12 ([successful docker image](https://hub.docker.com/layers/demisto/ldap/2.9.1.71992/images/sha256-6a5862828ce2e36423ac9a5b7b865e54c562f6efb85e738dfd66614af9f16637?context=explore)), the connection was successful.

Steps to reproduce: 
1. Import NTLM, ldap3
2. Create NTLM connection:
`conn = ldap3.Connection(server, domain_name, password=password, authentication=NTLM, auto_bind=auto_bind)`

Operating system: MAC, WINDOWS

Python version: 3.10.13

python-ldap version: 2.9.1 - 2021.07.18

**Comment by quanah** [comment]
ldap3 is not python-ldap

**Comment by quanah** [comment]
You can leave a bug report for ldap3 here, but I would not it does not appear to be maintained any longer. Also NTLM is insecure and should not be used. Since 2010, Microsoft no longer recommends NTLM in applications
