### ISSUE TITLE
Extended operations with unsolicited notifications... possible?

### ISSUE THREAD

**Issue by malibu1966** [python-ldap/python-ldap#580]
Hi there, I am delving into the world of ldap and I would like to use the LDAPv3 extended operation to notify on every ldap data change. This is requested as an extended operation (ldap.extop). The operation starts a stream of unsolicited notifications, but I don't see any way in the API to assign a handler callback. Is this possible with python-ldap?

Please describe the issue and your environment here.

---

Issue description:
How can I assign a callback handler for ldap unsolicited notifications?

Steps to reproduce: 
N/A

Operating system: 
Linux

Python version: 
3.11

python-ldap version: 
latest

**Comment by mistotebe** [comment]
You should be able to use `result4(ldap.RES_ANY, ldap.MSG_ALL, ...)` to receive them.

As an aside, it sounds like you're designing this protocol yourself, then you might want to reconsider the choice of unsolicited responses: you can get Intermediate responses to that extended operation instead and maintain the required context everywhere, also keep in mind that things like syncrepl `refreshAndPersist` exist that might be more than a good fit, depending what you're trying to achieve.

**Comment by mistotebe** [comment]
Sorry, I meant `ldap.MSG_ONE` above, not `ldap.MSG_ALL`.

**Comment by malibu1966** [comment]
What I'm trying to achieve is monitoring an ldap structure for any change and report as soon as anything changes.  I didn't want to do polling because that would be almost all unnecessary.

I don't know what you mean by 'designing a new protocol'.  I'm following ldapv3 documentation for extended operations.

**Comment by mistotebe** [comment]
Then you can just use syncrepl (RFC4533) and ask for refreshAndPesist. I meant "extension" when I said "protocol", sure, but the point still stands: a) this already exists and b) there are more client-friendly ways to design a new extension of this sort than relying on unsolicited responses.

**Comment by malibu1966** [comment]
I still don't understand why you are talking about creating something new.  This is a feature that is part of the LDAPv3 specification.

**Comment by mistotebe** [comment]
There is no mechanism for "monitoring an ldap structure for any change and report as soon as anything changes" that I know of exists and uses unsolicited notifications. That's what suggests to me you're trying to implement something new.

Anyway, so long as result4() works for you, I think we're off topic and this ticket can be considered resolved? Otherwise maybe reopen with new information.

**Comment by malibu1966** [comment]
The python ldap3 module has a single function to do it, documented [here](https://ldap3.readthedocs.io/en/latest/standard.html).  extend.standard.persistent_search is what I was looking for.  You set a callback to receive any logged change and process it.

**Comment by mistotebe** [comment]
That is not what you asked for, [persistent search](https://www.ietf.org/proceedings/50/I-D/ldapext-psearch-03.txt) does not use unsolicited responses in any way, as far as I can see in the document, the responses should carry the same msgid as the request that started them, where unsolicited responses use a msgid of 0 which is what makes them special.

And not many servers actually implement this, those that implement something to that effect tend to implement the [syncrepl control](https://datatracker.ietf.org/doc/html/rfc4533) instead. Regardless, you'd handle both in the same, pretty standard, way.

**Comment by malibu1966** [comment]
Maybe I used the wrong terminology.  I understood an unsolicited response as any response that could come afterwards independent of the original call, which is what persistent search does.
