### ISSUE TITLE
Rename ldap.async

### ISSUE THREAD

**Issue by encukou** [python-ldap/python-ldap#93]
In Python 3.7, `async` will become a keyword, and `import ldap.async` will fail.
Move the module, but ensure backwards compatibility for older Python versions.

**Comment by tiran** [comment]
Travis supports development versions of Python. Something like

```
    - python: 3.7-dev
      env:
        - TOXENV=py37
        - WITH_GCOV=1
```

should do the trick.

**Comment by encukou** [comment]
Yes. It should also be [allowed to fail](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail), at least until 3.7 is in beta.

**Comment by tiran** [comment]
Fixed in https://github.com/python-ldap/python-ldap/pull/107

I forgot to include the issue number in the PR, sorry.
